namespace WellSpent.Domain.Entities;

/// <summary>A spend, saving, or fixed expense within a period.</summary>
public sealed class Transaction
{
    public Guid Id { get; set; }
    public string? Name { get; set; }
    public decimal Amount { get; set; }
    public decimal PlannedAmount { get; set; }
    public DateOnly? Date { get; set; }
    public DateOnly? RenewalDate { get; set; }
    public Guid? BudgetPeriodId { get; set; }
    public int? CategoryId { get; set; }
    public Guid? PaymentMethodId { get; set; }
    public int? TransactionFrequencyId { get; set; }

    /// <summary>1 = Fixed, 2 = Variable.</summary>
    public int? TransactionTypeId { get; set; }

    public bool IsPaid { get; set; }
    public DateOnly? PaidDate { get; set; }

    /// <summary>Set when spawned from a FixedExpense template.</summary>
    public Guid? FixedExpenseId { get; set; }

    /// <summary>Backend-internal dedup key for a Plaid-imported row; never exposed on the wire — IsPlaidImported is derived from whether this is set.</summary>
    public string? PlaidTransactionId { get; set; }

    public bool IsExcluded { get; set; }

    /// <summary>Set when this transaction was converted into an installment plan. Also IsExcluded.</summary>
    public Guid? InstallmentFixedExpenseId { get; set; }

    /// <summary>Set when generated by carrying a closed period's ending balance into this one.</summary>
    public Guid? CarriedFromBudgetPeriodId { get; set; }

    public string? PlaidPfcPrimary { get; set; }
    public string? PlaidPfcDetailed { get; set; }
    public string? PlaidReferenceNumber { get; set; }
    public string? PlaidPpdId { get; set; }
}
