// Code generated by sqlc. DO NOT EDIT.
// This file will be regenerated by `sqlc generate`.

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

// ── Budgets ───────────────────────────────────────────────────────────────────

const listBudgetsByUser = `SELECT id, user_id, name, start_date, end_date, active FROM budget WHERE user_id = $1 ORDER BY active DESC, name`

func (q *Queries) ListBudgetsByUser(ctx context.Context, userID uuid.UUID) ([]Budget, error) {
	rows, err := q.db.Query(ctx, listBudgetsByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Budget
	for rows.Next() {
		var b Budget
		if err := rows.Scan(&b.ID, &b.UserID, &b.Name, &b.StartDate, &b.EndDate, &b.Active); err != nil {
			return nil, err
		}
		items = append(items, b)
	}
	return items, rows.Err()
}

const getBudgetByID = `SELECT id, user_id, name, start_date, end_date, active FROM budget WHERE id = $1 LIMIT 1`

func (q *Queries) GetBudgetByID(ctx context.Context, id uuid.UUID) (Budget, error) {
	row := q.db.QueryRow(ctx, getBudgetByID, id)
	var b Budget
	err := row.Scan(&b.ID, &b.UserID, &b.Name, &b.StartDate, &b.EndDate, &b.Active)
	return b, err
}

const existsBudgetByNameAndUser = `SELECT EXISTS (SELECT 1 FROM budget WHERE name = $1 AND user_id = $2) AS exists`

func (q *Queries) ExistsBudgetByNameAndUser(ctx context.Context, name string, userID uuid.UUID) (bool, error) {
	row := q.db.QueryRow(ctx, existsBudgetByNameAndUser, name, userID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

type CreateBudgetParams struct {
	UserID uuid.UUID
	Name   string
}

const createBudget = `INSERT INTO budget (user_id, name) VALUES ($1, $2) RETURNING id, user_id, name, start_date, end_date, active`

func (q *Queries) CreateBudget(ctx context.Context, arg CreateBudgetParams) (Budget, error) {
	row := q.db.QueryRow(ctx, createBudget, arg.UserID, arg.Name)
	var b Budget
	err := row.Scan(&b.ID, &b.UserID, &b.Name, &b.StartDate, &b.EndDate, &b.Active)
	return b, err
}

type UpdateBudgetParams struct {
	ID     uuid.UUID
	Name   string
	Active bool
}

const updateBudget = `UPDATE budget SET name = $2, active = $3 WHERE id = $1 RETURNING id, user_id, name, start_date, end_date, active`

func (q *Queries) UpdateBudget(ctx context.Context, arg UpdateBudgetParams) (Budget, error) {
	row := q.db.QueryRow(ctx, updateBudget, arg.ID, arg.Name, arg.Active)
	var b Budget
	err := row.Scan(&b.ID, &b.UserID, &b.Name, &b.StartDate, &b.EndDate, &b.Active)
	return b, err
}

const deleteBudget = `DELETE FROM budget WHERE id = $1`

func (q *Queries) DeleteBudget(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteBudget, id)
	return err
}

// ── People ────────────────────────────────────────────────────────────────────

const listBudgetPeople = `SELECT id, budget_id, user_name, user_id FROM budget_to_user_mapping WHERE budget_id = $1 ORDER BY id`

func (q *Queries) ListBudgetPeople(ctx context.Context, budgetID uuid.UUID) ([]BudgetToUserMapping, error) {
	rows, err := q.db.Query(ctx, listBudgetPeople, budgetID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []BudgetToUserMapping
	for rows.Next() {
		var m BudgetToUserMapping
		if err := rows.Scan(&m.ID, &m.BudgetID, &m.UserName, &m.UserID); err != nil {
			return nil, err
		}
		items = append(items, m)
	}
	return items, rows.Err()
}

const existsBudgetPerson = `SELECT EXISTS (SELECT 1 FROM budget_to_user_mapping WHERE budget_id = $1 AND user_name = $2) AS exists`

func (q *Queries) ExistsBudgetPerson(ctx context.Context, budgetID uuid.UUID, userName string) (bool, error) {
	row := q.db.QueryRow(ctx, existsBudgetPerson, budgetID, userName)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

type AddBudgetPersonParams struct {
	BudgetID uuid.UUID
	UserName *string
	UserID   *uuid.UUID
}

const addBudgetPerson = `INSERT INTO budget_to_user_mapping (budget_id, user_name, user_id) VALUES ($1, $2, $3) RETURNING id, budget_id, user_name, user_id`

func (q *Queries) AddBudgetPerson(ctx context.Context, arg AddBudgetPersonParams) (BudgetToUserMapping, error) {
	row := q.db.QueryRow(ctx, addBudgetPerson, arg.BudgetID, arg.UserName, arg.UserID)
	var m BudgetToUserMapping
	err := row.Scan(&m.ID, &m.BudgetID, &m.UserName, &m.UserID)
	return m, err
}

type RemoveBudgetPersonParams struct {
	ID       int32
	BudgetID uuid.UUID
}

const removeBudgetPerson = `DELETE FROM budget_to_user_mapping WHERE id = $1 AND budget_id = $2`

func (q *Queries) RemoveBudgetPerson(ctx context.Context, arg RemoveBudgetPersonParams) error {
	_, err := q.db.Exec(ctx, removeBudgetPerson, arg.ID, arg.BudgetID)
	return err
}

// ── Income ────────────────────────────────────────────────────────────────────

const listIncomeEntries = `SELECT id, budget_id, user_id, name, amount, recurring FROM income_to_budget_mapping WHERE budget_id = $1 ORDER BY id`

func (q *Queries) ListIncomeEntries(ctx context.Context, budgetID uuid.UUID) ([]IncomeToBudgetMapping, error) {
	rows, err := q.db.Query(ctx, listIncomeEntries, budgetID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []IncomeToBudgetMapping
	for rows.Next() {
		var m IncomeToBudgetMapping
		if err := rows.Scan(&m.ID, &m.BudgetID, &m.UserID, &m.Name, &m.Amount, &m.Recurring); err != nil {
			return nil, err
		}
		items = append(items, m)
	}
	return items, rows.Err()
}

type AddIncomeEntryParams struct {
	BudgetID  uuid.UUID
	UserID    *uuid.UUID
	Name      *string
	Amount    pgtype.Numeric
	Recurring bool
}

const addIncomeEntry = `INSERT INTO income_to_budget_mapping (budget_id, user_id, name, amount, recurring) VALUES ($1, $2, $3, $4, $5) RETURNING id, budget_id, user_id, name, amount, recurring`

func (q *Queries) AddIncomeEntry(ctx context.Context, arg AddIncomeEntryParams) (IncomeToBudgetMapping, error) {
	row := q.db.QueryRow(ctx, addIncomeEntry, arg.BudgetID, arg.UserID, arg.Name, arg.Amount, arg.Recurring)
	var m IncomeToBudgetMapping
	err := row.Scan(&m.ID, &m.BudgetID, &m.UserID, &m.Name, &m.Amount, &m.Recurring)
	return m, err
}

type UpdateIncomeEntryParams struct {
	ID        int32
	BudgetID  uuid.UUID
	Name      *string
	Amount    pgtype.Numeric
	Recurring bool
}

const updateIncomeEntry = `UPDATE income_to_budget_mapping SET name = $3, amount = $4, recurring = $5 WHERE id = $1 AND budget_id = $2 RETURNING id, budget_id, user_id, name, amount, recurring`

func (q *Queries) UpdateIncomeEntry(ctx context.Context, arg UpdateIncomeEntryParams) (IncomeToBudgetMapping, error) {
	row := q.db.QueryRow(ctx, updateIncomeEntry, arg.ID, arg.BudgetID, arg.Name, arg.Amount, arg.Recurring)
	var m IncomeToBudgetMapping
	err := row.Scan(&m.ID, &m.BudgetID, &m.UserID, &m.Name, &m.Amount, &m.Recurring)
	return m, err
}

type DeleteIncomeEntryParams struct {
	ID       int32
	BudgetID uuid.UUID
}

const deleteIncomeEntry = `DELETE FROM income_to_budget_mapping WHERE id = $1 AND budget_id = $2`

func (q *Queries) DeleteIncomeEntry(ctx context.Context, arg DeleteIncomeEntryParams) error {
	_, err := q.db.Exec(ctx, deleteIncomeEntry, arg.ID, arg.BudgetID)
	return err
}
