// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: changelog.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createChangelogItem = `-- name: CreateChangelogItem :one
INSERT INTO changelog_item (release_id, change_type, summary_en, summary_es, position)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, release_id, change_type, summary_en, summary_es, position, created_at
`

type CreateChangelogItemParams struct {
	ReleaseID  uuid.UUID `json:"release_id"`
	ChangeType string    `json:"change_type"`
	SummaryEn  string    `json:"summary_en"`
	SummaryEs  string    `json:"summary_es"`
	Position   int32     `json:"position"`
}

func (q *Queries) CreateChangelogItem(ctx context.Context, arg CreateChangelogItemParams) (ChangelogItem, error) {
	row := q.db.QueryRow(ctx, createChangelogItem,
		arg.ReleaseID,
		arg.ChangeType,
		arg.SummaryEn,
		arg.SummaryEs,
		arg.Position,
	)
	var i ChangelogItem
	err := row.Scan(
		&i.ID,
		&i.ReleaseID,
		&i.ChangeType,
		&i.SummaryEn,
		&i.SummaryEs,
		&i.Position,
		&i.CreatedAt,
	)
	return i, err
}

const createChangelogRelease = `-- name: CreateChangelogRelease :one
INSERT INTO changelog_release (component, version, released_at, created_by)
VALUES ($1, $2, $3, $4)
RETURNING id, component, version, released_at, created_by, created_at
`

type CreateChangelogReleaseParams struct {
	Component  string             `json:"component"`
	Version    string             `json:"version"`
	ReleasedAt pgtype.Timestamptz `json:"released_at"`
	CreatedBy  uuid.UUID          `json:"created_by"`
}

// released_at is always supplied by the caller (defaulted to now in the
// service) rather than relying on the column default, so one code path decides
// it. A duplicate (component, version) violates the unique constraint, which
// the service maps to a Duplicate error.
func (q *Queries) CreateChangelogRelease(ctx context.Context, arg CreateChangelogReleaseParams) (ChangelogRelease, error) {
	row := q.db.QueryRow(ctx, createChangelogRelease,
		arg.Component,
		arg.Version,
		arg.ReleasedAt,
		arg.CreatedBy,
	)
	var i ChangelogRelease
	err := row.Scan(
		&i.ID,
		&i.Component,
		&i.Version,
		&i.ReleasedAt,
		&i.CreatedBy,
		&i.CreatedAt,
	)
	return i, err
}

const listChangelogItemsForReleases = `-- name: ListChangelogItemsForReleases :many
SELECT id, release_id, change_type, summary_en, summary_es, position, created_at
FROM changelog_item
WHERE release_id = ANY ($1::uuid[])
ORDER BY release_id, position, created_at
`

// Every item for a set of releases in one round trip, rather than one query
// per release — the Help browser can ask for dozens at a time.
func (q *Queries) ListChangelogItemsForReleases(ctx context.Context, releaseIds []uuid.UUID) ([]ChangelogItem, error) {
	rows, err := q.db.Query(ctx, listChangelogItemsForReleases, releaseIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ChangelogItem
	for rows.Next() {
		var i ChangelogItem
		if err := rows.Scan(
			&i.ID,
			&i.ReleaseID,
			&i.ChangeType,
			&i.SummaryEn,
			&i.SummaryEs,
			&i.Position,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listChangelogReleases = `-- name: ListChangelogReleases :many
SELECT id, component, version, released_at, created_by, created_at
FROM changelog_release
WHERE cardinality($1::text[]) = 0
   OR component = ANY ($1::text[])
ORDER BY component, released_at DESC, created_at DESC
`

// Newest first per component. The caller passes the components it wants — a
// client asks for its own plus 'server'; the Help browser asks for all three.
// An empty array means all, so the "browse everything" case needs no second
// query.
func (q *Queries) ListChangelogReleases(ctx context.Context, components []string) ([]ChangelogRelease, error) {
	rows, err := q.db.Query(ctx, listChangelogReleases, components)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ChangelogRelease
	for rows.Next() {
		var i ChangelogRelease
		if err := rows.Scan(
			&i.ID,
			&i.Component,
			&i.Version,
			&i.ReleasedAt,
			&i.CreatedBy,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
