// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: device_token.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const listDeviceTokensForUser = `-- name: ListDeviceTokensForUser :many
SELECT id, user_id, platform, token, created_at, updated_at
FROM device_token
WHERE user_id = $1
`

func (q *Queries) ListDeviceTokensForUser(ctx context.Context, userID uuid.UUID) ([]DeviceToken, error) {
	rows, err := q.db.Query(ctx, listDeviceTokensForUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []DeviceToken
	for rows.Next() {
		var i DeviceToken
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Platform,
			&i.Token,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertDeviceToken = `-- name: UpsertDeviceToken :one
INSERT INTO device_token (user_id, platform, token)
VALUES ($1, $2, $3)
ON CONFLICT (token)
DO UPDATE SET
    user_id    = EXCLUDED.user_id,
    platform   = EXCLUDED.platform,
    updated_at = NOW()
RETURNING id, user_id, platform, token, created_at, updated_at
`

type UpsertDeviceTokenParams struct {
	UserID   uuid.UUID `json:"user_id"`
	Platform string    `json:"platform"`
	Token    string    `json:"token"`
}

func (q *Queries) UpsertDeviceToken(ctx context.Context, arg UpsertDeviceTokenParams) (DeviceToken, error) {
	row := q.db.QueryRow(ctx, upsertDeviceToken, arg.UserID, arg.Platform, arg.Token)
	var i DeviceToken
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Platform,
		&i.Token,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
