// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: notification.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createNotification = `-- name: CreateNotification :one

INSERT INTO notification (user_id, budget_profile_id, alert_type, title, body)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, user_id, budget_profile_id, alert_type, title, body, is_read, created_at
`

type CreateNotificationParams struct {
	UserID          uuid.UUID  `json:"user_id"`
	BudgetProfileID *uuid.UUID `json:"budget_profile_id"`
	AlertType       string     `json:"alert_type"`
	Title           string     `json:"title"`
	Body            string     `json:"body"`
}

// ─── Notifications ────────────────────────────────────────────────────────────
func (q *Queries) CreateNotification(ctx context.Context, arg CreateNotificationParams) (Notification, error) {
	row := q.db.QueryRow(ctx, createNotification,
		arg.UserID,
		arg.BudgetProfileID,
		arg.AlertType,
		arg.Title,
		arg.Body,
	)
	var i Notification
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.BudgetProfileID,
		&i.AlertType,
		&i.Title,
		&i.Body,
		&i.IsRead,
		&i.CreatedAt,
	)
	return i, err
}

const deleteAlertSubscription = `-- name: DeleteAlertSubscription :exec
DELETE FROM alert_subscription WHERE id = $1 AND user_id = $2
`

type DeleteAlertSubscriptionParams struct {
	ID     uuid.UUID `json:"id"`
	UserID uuid.UUID `json:"user_id"`
}

func (q *Queries) DeleteAlertSubscription(ctx context.Context, arg DeleteAlertSubscriptionParams) error {
	_, err := q.db.Exec(ctx, deleteAlertSubscription, arg.ID, arg.UserID)
	return err
}

const getAlertSubscription = `-- name: GetAlertSubscription :one
SELECT id, user_id, budget_profile_id, alert_type, channel,
       threshold_pct, threshold_scope, category_id, notify_all_members, created_at
FROM alert_subscription
WHERE id = $1 AND user_id = $2
`

type GetAlertSubscriptionParams struct {
	ID     uuid.UUID `json:"id"`
	UserID uuid.UUID `json:"user_id"`
}

func (q *Queries) GetAlertSubscription(ctx context.Context, arg GetAlertSubscriptionParams) (AlertSubscription, error) {
	row := q.db.QueryRow(ctx, getAlertSubscription, arg.ID, arg.UserID)
	var i AlertSubscription
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.BudgetProfileID,
		&i.AlertType,
		&i.Channel,
		&i.ThresholdPct,
		&i.ThresholdScope,
		&i.CategoryID,
		&i.NotifyAllMembers,
		&i.CreatedAt,
	)
	return i, err
}

const getBudgetAlertSubscribers = `-- name: GetBudgetAlertSubscribers :many
SELECT id, user_id, budget_profile_id, alert_type, channel,
       threshold_pct, threshold_scope, category_id, notify_all_members, created_at
FROM alert_subscription
WHERE budget_profile_id = $1 AND alert_type = $2
`

type GetBudgetAlertSubscribersParams struct {
	BudgetProfileID uuid.UUID `json:"budget_profile_id"`
	AlertType       string    `json:"alert_type"`
}

// Get all subscribers for an event on a budget (for notification fan-out).
func (q *Queries) GetBudgetAlertSubscribers(ctx context.Context, arg GetBudgetAlertSubscribersParams) ([]AlertSubscription, error) {
	rows, err := q.db.Query(ctx, getBudgetAlertSubscribers, arg.BudgetProfileID, arg.AlertType)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AlertSubscription
	for rows.Next() {
		var i AlertSubscription
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.BudgetProfileID,
			&i.AlertType,
			&i.Channel,
			&i.ThresholdPct,
			&i.ThresholdScope,
			&i.CategoryID,
			&i.NotifyAllMembers,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUnreadCount = `-- name: GetUnreadCount :one
SELECT COUNT(*)::int AS count
FROM notification
WHERE user_id = $1 AND is_read = FALSE
`

func (q *Queries) GetUnreadCount(ctx context.Context, userID uuid.UUID) (int32, error) {
	row := q.db.QueryRow(ctx, getUnreadCount, userID)
	var count int32
	err := row.Scan(&count)
	return count, err
}

const listAlertSubscriptions = `-- name: ListAlertSubscriptions :many

SELECT id, user_id, budget_profile_id, alert_type, channel,
       threshold_pct, threshold_scope, category_id, notify_all_members, created_at
FROM alert_subscription
WHERE user_id = $1 AND budget_profile_id = $2
ORDER BY created_at
`

type ListAlertSubscriptionsParams struct {
	UserID          uuid.UUID `json:"user_id"`
	BudgetProfileID uuid.UUID `json:"budget_profile_id"`
}

// ─── Alert subscriptions ──────────────────────────────────────────────────────
func (q *Queries) ListAlertSubscriptions(ctx context.Context, arg ListAlertSubscriptionsParams) ([]AlertSubscription, error) {
	rows, err := q.db.Query(ctx, listAlertSubscriptions, arg.UserID, arg.BudgetProfileID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AlertSubscription
	for rows.Next() {
		var i AlertSubscription
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.BudgetProfileID,
			&i.AlertType,
			&i.Channel,
			&i.ThresholdPct,
			&i.ThresholdScope,
			&i.CategoryID,
			&i.NotifyAllMembers,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listNotifications = `-- name: ListNotifications :many
SELECT id, user_id, budget_profile_id, alert_type, title, body, is_read, created_at
FROM notification
WHERE user_id = $1
  AND ($2::uuid IS NULL OR budget_profile_id = $2)
ORDER BY created_at DESC
LIMIT $3::int
`

type ListNotificationsParams struct {
	UserID          uuid.UUID `json:"user_id"`
	BudgetProfileID uuid.UUID `json:"budget_profile_id"`
	LimitVal        int32     `json:"limit_val"`
}

func (q *Queries) ListNotifications(ctx context.Context, arg ListNotificationsParams) ([]Notification, error) {
	rows, err := q.db.Query(ctx, listNotifications, arg.UserID, arg.BudgetProfileID, arg.LimitVal)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Notification
	for rows.Next() {
		var i Notification
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.BudgetProfileID,
			&i.AlertType,
			&i.Title,
			&i.Body,
			&i.IsRead,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markNotificationsRead = `-- name: MarkNotificationsRead :exec
UPDATE notification
SET is_read = TRUE
WHERE user_id = $1
  AND (ARRAY_LENGTH($2::uuid[], 1) IS NULL OR id = ANY($2::uuid[]))
`

type MarkNotificationsReadParams struct {
	UserID uuid.UUID   `json:"user_id"`
	Ids    []uuid.UUID `json:"ids"`
}

func (q *Queries) MarkNotificationsRead(ctx context.Context, arg MarkNotificationsReadParams) error {
	_, err := q.db.Exec(ctx, markNotificationsRead, arg.UserID, arg.Ids)
	return err
}

const upsertAlertSubscription = `-- name: UpsertAlertSubscription :one
INSERT INTO alert_subscription
    (user_id, budget_profile_id, alert_type, channel, threshold_pct, threshold_scope, category_id, notify_all_members)
VALUES
    ($1, $2, $3, $4,
     $5, $6, $7, $8)
ON CONFLICT (user_id, budget_profile_id, alert_type, COALESCE(category_id, -1))
DO UPDATE SET
    channel            = EXCLUDED.channel,
    threshold_pct      = EXCLUDED.threshold_pct,
    threshold_scope    = EXCLUDED.threshold_scope,
    notify_all_members = EXCLUDED.notify_all_members
RETURNING id, user_id, budget_profile_id, alert_type, channel,
          threshold_pct, threshold_scope, category_id, notify_all_members, created_at
`

type UpsertAlertSubscriptionParams struct {
	UserID           uuid.UUID      `json:"user_id"`
	BudgetProfileID  uuid.UUID      `json:"budget_profile_id"`
	AlertType        string         `json:"alert_type"`
	Channel          string         `json:"channel"`
	ThresholdPct     pgtype.Numeric `json:"threshold_pct"`
	ThresholdScope   *string        `json:"threshold_scope"`
	CategoryID       *int32         `json:"category_id"`
	NotifyAllMembers bool           `json:"notify_all_members"`
}

func (q *Queries) UpsertAlertSubscription(ctx context.Context, arg UpsertAlertSubscriptionParams) (AlertSubscription, error) {
	row := q.db.QueryRow(ctx, upsertAlertSubscription,
		arg.UserID,
		arg.BudgetProfileID,
		arg.AlertType,
		arg.Channel,
		arg.ThresholdPct,
		arg.ThresholdScope,
		arg.CategoryID,
		arg.NotifyAllMembers,
	)
	var i AlertSubscription
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.BudgetProfileID,
		&i.AlertType,
		&i.Channel,
		&i.ThresholdPct,
		&i.ThresholdScope,
		&i.CategoryID,
		&i.NotifyAllMembers,
		&i.CreatedAt,
	)
	return i, err
}
