// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: status_banner.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createStatusBanner = `-- name: CreateStatusBanner :one
INSERT INTO status_banner (severity, message_en, message_es, starts_at, ends_at, created_by)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, severity, message_en, message_es, starts_at, ends_at, created_by, created_at
`

type CreateStatusBannerParams struct {
	Severity  string             `json:"severity"`
	MessageEn string             `json:"message_en"`
	MessageEs string             `json:"message_es"`
	StartsAt  pgtype.Timestamptz `json:"starts_at"`
	EndsAt    pgtype.Timestamptz `json:"ends_at"`
	CreatedBy uuid.UUID          `json:"created_by"`
}

// starts_at is always supplied by the caller (defaulted to now in the service)
// rather than relying on the column default, so one code path decides it.
func (q *Queries) CreateStatusBanner(ctx context.Context, arg CreateStatusBannerParams) (StatusBanner, error) {
	row := q.db.QueryRow(ctx, createStatusBanner,
		arg.Severity,
		arg.MessageEn,
		arg.MessageEs,
		arg.StartsAt,
		arg.EndsAt,
		arg.CreatedBy,
	)
	var i StatusBanner
	err := row.Scan(
		&i.ID,
		&i.Severity,
		&i.MessageEn,
		&i.MessageEs,
		&i.StartsAt,
		&i.EndsAt,
		&i.CreatedBy,
		&i.CreatedAt,
	)
	return i, err
}

const expireStatusBanner = `-- name: ExpireStatusBanner :one
UPDATE status_banner
SET ends_at = LEAST(ends_at, GREATEST(starts_at, NOW()))
WHERE id = $1
RETURNING id, severity, message_en, message_es, starts_at, ends_at, created_by, created_at
`

// Takes a banner down early. LEAST/GREATEST keeps this correct for all three
// states without a branch in Go, and never violates the ends_at >= starts_at
// constraint:
//
//	live      → ends_at = NOW()      (stops showing now)
//	scheduled → ends_at = starts_at  (empty window, never shows)
//	expired   → unchanged            (history is not rewritten)
func (q *Queries) ExpireStatusBanner(ctx context.Context, id uuid.UUID) (StatusBanner, error) {
	row := q.db.QueryRow(ctx, expireStatusBanner, id)
	var i StatusBanner
	err := row.Scan(
		&i.ID,
		&i.Severity,
		&i.MessageEn,
		&i.MessageEs,
		&i.StartsAt,
		&i.EndsAt,
		&i.CreatedBy,
		&i.CreatedAt,
	)
	return i, err
}

const getActiveStatusBanner = `-- name: GetActiveStatusBanner :one
SELECT id, severity, message_en, message_es, starts_at, ends_at, created_by, created_at
FROM status_banner
WHERE starts_at <= NOW()
  AND ends_at > NOW()
ORDER BY
    CASE severity
        WHEN 'critical' THEN 3
        WHEN 'warning' THEN 2
        ELSE 1
    END DESC,
    created_at DESC
LIMIT 1
`

// At most one banner is ever shown, so the tie-break is part of the contract
// rather than left to the client: highest severity first, then most recently
// created. Severity is stored as text for readability in psql during an
// incident, so the ordering is spelled out here.
func (q *Queries) GetActiveStatusBanner(ctx context.Context) (StatusBanner, error) {
	row := q.db.QueryRow(ctx, getActiveStatusBanner)
	var i StatusBanner
	err := row.Scan(
		&i.ID,
		&i.Severity,
		&i.MessageEn,
		&i.MessageEs,
		&i.StartsAt,
		&i.EndsAt,
		&i.CreatedBy,
		&i.CreatedAt,
	)
	return i, err
}

const listStatusBanners = `-- name: ListStatusBanners :many
SELECT id, severity, message_en, message_es, starts_at, ends_at, created_by, created_at
FROM status_banner
ORDER BY created_at DESC
LIMIT $1
`

// The operator's history, including expired rows — not the client-facing view.
func (q *Queries) ListStatusBanners(ctx context.Context, limit int32) ([]StatusBanner, error) {
	rows, err := q.db.Query(ctx, listStatusBanners, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []StatusBanner
	for rows.Next() {
		var i StatusBanner
		if err := rows.Scan(
			&i.ID,
			&i.Severity,
			&i.MessageEn,
			&i.MessageEs,
			&i.StartsAt,
			&i.EndsAt,
			&i.CreatedBy,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
