// Code generated by sqlc. DO NOT EDIT.
// This file will be regenerated by `sqlc generate`.

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

// ── Transactions ──────────────────────────────────────────────────────────────

type ListTransactionsParams struct {
	BudgetID          uuid.UUID
	CategoryID        *int32
	TransactionTypeID *int32
}

const listTransactions = `SELECT id, name, amount, planned_amount, date, renewal_date, recurring, budget_id, category_id, payment_method_id, transaction_frequency_id, transaction_type_id FROM transaction WHERE budget_id = $1 AND ($2::int IS NULL OR category_id = $2) AND ($3::int IS NULL OR transaction_type_id = $3) ORDER BY date DESC NULLS LAST`

func (q *Queries) ListTransactions(ctx context.Context, arg ListTransactionsParams) ([]Transaction, error) {
	rows, err := q.db.Query(ctx, listTransactions, arg.BudgetID, arg.CategoryID, arg.TransactionTypeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Transaction
	for rows.Next() {
		var t Transaction
		if err := rows.Scan(&t.ID, &t.Name, &t.Amount, &t.PlannedAmount, &t.Date, &t.RenewalDate,
			&t.Recurring, &t.BudgetID, &t.CategoryID, &t.PaymentMethodID,
			&t.TransactionFrequencyID, &t.TransactionTypeID); err != nil {
			return nil, err
		}
		items = append(items, t)
	}
	return items, rows.Err()
}

const getTransactionByID = `SELECT id, name, amount, planned_amount, date, renewal_date, recurring, budget_id, category_id, payment_method_id, transaction_frequency_id, transaction_type_id FROM transaction WHERE id = $1 LIMIT 1`

func (q *Queries) GetTransactionByID(ctx context.Context, id uuid.UUID) (Transaction, error) {
	row := q.db.QueryRow(ctx, getTransactionByID, id)
	var t Transaction
	err := row.Scan(&t.ID, &t.Name, &t.Amount, &t.PlannedAmount, &t.Date, &t.RenewalDate,
		&t.Recurring, &t.BudgetID, &t.CategoryID, &t.PaymentMethodID,
		&t.TransactionFrequencyID, &t.TransactionTypeID)
	return t, err
}

type CreateTransactionParams struct {
	Name                   *string
	Amount                 pgtype.Numeric
	PlannedAmount          pgtype.Numeric
	Date                   pgtype.Date
	RenewalDate            pgtype.Date
	Recurring              *bool
	BudgetID               *uuid.UUID
	CategoryID             *int32
	PaymentMethodID        *uuid.UUID
	TransactionFrequencyID *int32
	TransactionTypeID      *int32
}

const createTransaction = `INSERT INTO transaction (name, amount, planned_amount, date, renewal_date, recurring, budget_id, category_id, payment_method_id, transaction_frequency_id, transaction_type_id) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11) RETURNING id, name, amount, planned_amount, date, renewal_date, recurring, budget_id, category_id, payment_method_id, transaction_frequency_id, transaction_type_id`

func (q *Queries) CreateTransaction(ctx context.Context, arg CreateTransactionParams) (Transaction, error) {
	row := q.db.QueryRow(ctx, createTransaction,
		arg.Name, arg.Amount, arg.PlannedAmount, arg.Date, arg.RenewalDate, arg.Recurring,
		arg.BudgetID, arg.CategoryID, arg.PaymentMethodID,
		arg.TransactionFrequencyID, arg.TransactionTypeID)
	var t Transaction
	err := row.Scan(&t.ID, &t.Name, &t.Amount, &t.PlannedAmount, &t.Date, &t.RenewalDate,
		&t.Recurring, &t.BudgetID, &t.CategoryID, &t.PaymentMethodID,
		&t.TransactionFrequencyID, &t.TransactionTypeID)
	return t, err
}

type UpdateTransactionParams struct {
	ID                     uuid.UUID
	Name                   *string
	Amount                 pgtype.Numeric
	PlannedAmount          pgtype.Numeric
	Date                   pgtype.Date
	Recurring              *bool
	CategoryID             *int32
	PaymentMethodID        *uuid.UUID
	TransactionFrequencyID *int32
	TransactionTypeID      *int32
}

const updateTransaction = `UPDATE transaction SET name = $2, amount = $3, planned_amount = $4, date = $5, recurring = $6, category_id = $7, payment_method_id = $8, transaction_frequency_id = $9, transaction_type_id = $10 WHERE id = $1 RETURNING id, name, amount, planned_amount, date, renewal_date, recurring, budget_id, category_id, payment_method_id, transaction_frequency_id, transaction_type_id`

func (q *Queries) UpdateTransaction(ctx context.Context, arg UpdateTransactionParams) (Transaction, error) {
	row := q.db.QueryRow(ctx, updateTransaction,
		arg.ID, arg.Name, arg.Amount, arg.PlannedAmount, arg.Date, arg.Recurring,
		arg.CategoryID, arg.PaymentMethodID, arg.TransactionFrequencyID, arg.TransactionTypeID)
	var t Transaction
	err := row.Scan(&t.ID, &t.Name, &t.Amount, &t.PlannedAmount, &t.Date, &t.RenewalDate,
		&t.Recurring, &t.BudgetID, &t.CategoryID, &t.PaymentMethodID,
		&t.TransactionFrequencyID, &t.TransactionTypeID)
	return t, err
}

type DeleteTransactionParams struct {
	ID       uuid.UUID
	BudgetID uuid.UUID
}

const deleteTransaction = `DELETE FROM transaction WHERE id = $1 AND budget_id = $2`

func (q *Queries) DeleteTransaction(ctx context.Context, arg DeleteTransactionParams) error {
	_, err := q.db.Exec(ctx, deleteTransaction, arg.ID, arg.BudgetID)
	return err
}

// ── Categories ────────────────────────────────────────────────────────────────

const listCategories = `SELECT id, name, type_id, user_id FROM category WHERE user_id = $1 OR user_id IS NULL ORDER BY name`

func (q *Queries) ListCategories(ctx context.Context, userID *uuid.UUID) ([]Category, error) {
	rows, err := q.db.Query(ctx, listCategories, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Category
	for rows.Next() {
		var c Category
		if err := rows.Scan(&c.ID, &c.Name, &c.TypeID, &c.UserID); err != nil {
			return nil, err
		}
		items = append(items, c)
	}
	return items, rows.Err()
}

type CreateCategoryParams struct {
	Name   string
	TypeID *int32
	UserID *uuid.UUID
}

const createCategory = `INSERT INTO category (name, type_id, user_id) VALUES ($1, $2, $3) RETURNING id, name, type_id, user_id`

func (q *Queries) CreateCategory(ctx context.Context, arg CreateCategoryParams) (Category, error) {
	row := q.db.QueryRow(ctx, createCategory, arg.Name, arg.TypeID, arg.UserID)
	var c Category
	err := row.Scan(&c.ID, &c.Name, &c.TypeID, &c.UserID)
	return c, err
}

// ── Payment methods ───────────────────────────────────────────────────────────

type ListPaymentMethodsRow struct {
	PaymentMethod
	TypeName *string `json:"type_name"`
}

const listPaymentMethods = `SELECT pm.id, pm.name, pm.payment_type_id, pm.user_id, pt.name AS type_name FROM payment_method pm LEFT JOIN payment_type pt ON pm.payment_type_id = pt.id WHERE pm.user_id = $1 ORDER BY pm.name`

func (q *Queries) ListPaymentMethods(ctx context.Context, userID uuid.UUID) ([]ListPaymentMethodsRow, error) {
	rows, err := q.db.Query(ctx, listPaymentMethods, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPaymentMethodsRow
	for rows.Next() {
		var r ListPaymentMethodsRow
		if err := rows.Scan(&r.ID, &r.Name, &r.PaymentTypeID, &r.UserID, &r.TypeName); err != nil {
			return nil, err
		}
		items = append(items, r)
	}
	return items, rows.Err()
}

type CreatePaymentMethodParams struct {
	Name          string
	PaymentTypeID *int32
	UserID        *uuid.UUID
}

const createPaymentMethod = `INSERT INTO payment_method (name, payment_type_id, user_id) VALUES ($1, $2, $3) RETURNING id, name, payment_type_id, user_id`

func (q *Queries) CreatePaymentMethod(ctx context.Context, arg CreatePaymentMethodParams) (PaymentMethod, error) {
	row := q.db.QueryRow(ctx, createPaymentMethod, arg.Name, arg.PaymentTypeID, arg.UserID)
	var m PaymentMethod
	err := row.Scan(&m.ID, &m.Name, &m.PaymentTypeID, &m.UserID)
	return m, err
}

// ── Reference data ────────────────────────────────────────────────────────────

const listTransactionTypes = `SELECT id, name FROM transaction_type ORDER BY id`

func (q *Queries) ListTransactionTypes(ctx context.Context) ([]TransactionType, error) {
	rows, err := q.db.Query(ctx, listTransactionTypes)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []TransactionType
	for rows.Next() {
		var t TransactionType
		if err := rows.Scan(&t.ID, &t.Name); err != nil {
			return nil, err
		}
		items = append(items, t)
	}
	return items, rows.Err()
}

const listTransactionFrequencies = `SELECT id, name FROM transaction_frequency ORDER BY id`

func (q *Queries) ListTransactionFrequencies(ctx context.Context) ([]TransactionFrequency, error) {
	rows, err := q.db.Query(ctx, listTransactionFrequencies)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []TransactionFrequency
	for rows.Next() {
		var f TransactionFrequency
		if err := rows.Scan(&f.ID, &f.Name); err != nil {
			return nil, err
		}
		items = append(items, f)
	}
	return items, rows.Err()
}
