// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: transaction.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const clearTransactionInstallmentPlan = `-- name: ClearTransactionInstallmentPlan :one
UPDATE transaction
SET is_excluded = FALSE,
    installment_fixed_expense_id = NULL
WHERE id = $1::uuid
  AND budget_period_id = $2::uuid
RETURNING id, name, amount, planned_amount, date, renewal_date,
          budget_period_id, category_id, payment_method_id, transaction_frequency_id, transaction_type_id,
          is_paid, paid_date, fixed_expense_id, plaid_transaction_id, is_excluded, installment_fixed_expense_id, carried_from_budget_period_id,
       plaid_pfc_primary, plaid_pfc_detailed, plaid_reference_number, plaid_ppd_id
`

type ClearTransactionInstallmentPlanParams struct {
	ID             uuid.UUID `json:"id"`
	BudgetPeriodID uuid.UUID `json:"budget_period_id"`
}

// Reverses an installment split: the purchase counts again and forgets the plan
// it briefly became. Paired with deleting the plan and its spawned payments in
// the service (issue #54).
func (q *Queries) ClearTransactionInstallmentPlan(ctx context.Context, arg ClearTransactionInstallmentPlanParams) (Transaction, error) {
	row := q.db.QueryRow(ctx, clearTransactionInstallmentPlan, arg.ID, arg.BudgetPeriodID)
	var i Transaction
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Amount,
		&i.PlannedAmount,
		&i.Date,
		&i.RenewalDate,
		&i.BudgetPeriodID,
		&i.CategoryID,
		&i.PaymentMethodID,
		&i.TransactionFrequencyID,
		&i.TransactionTypeID,
		&i.IsPaid,
		&i.PaidDate,
		&i.FixedExpenseID,
		&i.PlaidTransactionID,
		&i.IsExcluded,
		&i.InstallmentFixedExpenseID,
		&i.CarriedFromBudgetPeriodID,
		&i.PlaidPfcPrimary,
		&i.PlaidPfcDetailed,
		&i.PlaidReferenceNumber,
		&i.PlaidPpdID,
	)
	return i, err
}

const countCarriedTransactions = `-- name: CountCarriedTransactions :one
SELECT COUNT(*) FROM transaction
WHERE budget_period_id = $1::uuid
  AND carried_from_budget_period_id = $2::uuid
`

type CountCarriedTransactionsParams struct {
	BudgetPeriodID            uuid.UUID `json:"budget_period_id"`
	CarriedFromBudgetPeriodID uuid.UUID `json:"carried_from_budget_period_id"`
}

// Idempotency guard for the carryover step. createNextPeriod has no transaction
// wrapper and is reachable both from the daily cycling job and from a
// client-callable RPC, so it has to be able to tell that a given closing
// period's balance was already carried into a given new period.
func (q *Queries) CountCarriedTransactions(ctx context.Context, arg CountCarriedTransactionsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countCarriedTransactions, arg.BudgetPeriodID, arg.CarriedFromBudgetPeriodID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createCategory = `-- name: CreateCategory :one
INSERT INTO category (name, type_id, user_id, color)
VALUES (
    $1,
    (SELECT id FROM category_type WHERE name = 'Expense'),
    $2::uuid,
    $3
)
RETURNING id, name, type_id, is_system, user_id, color, system_key
`

type CreateCategoryParams struct {
	Name   string    `json:"name"`
	UserID uuid.UUID `json:"user_id"`
	Color  string    `json:"color"`
}

type CreateCategoryRow struct {
	ID        int32      `json:"id"`
	Name      string     `json:"name"`
	TypeID    *int32     `json:"type_id"`
	IsSystem  bool       `json:"is_system"`
	UserID    *uuid.UUID `json:"user_id"`
	Color     string     `json:"color"`
	SystemKey *string    `json:"system_key"`
}

func (q *Queries) CreateCategory(ctx context.Context, arg CreateCategoryParams) (CreateCategoryRow, error) {
	row := q.db.QueryRow(ctx, createCategory, arg.Name, arg.UserID, arg.Color)
	var i CreateCategoryRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.TypeID,
		&i.IsSystem,
		&i.UserID,
		&i.Color,
		&i.SystemKey,
	)
	return i, err
}

const createPaymentMethod = `-- name: CreatePaymentMethod :one
INSERT INTO payment_methods (name, payment_type_id, user_id, budget_person_id, color)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, name, payment_type_id, user_id, is_active, budget_person_id, color, plaid_account_id, alias, plaid_item_id
`

type CreatePaymentMethodParams struct {
	Name           string     `json:"name"`
	PaymentTypeID  *int32     `json:"payment_type_id"`
	UserID         *uuid.UUID `json:"user_id"`
	BudgetPersonID *int32     `json:"budget_person_id"`
	Color          string     `json:"color"`
}

func (q *Queries) CreatePaymentMethod(ctx context.Context, arg CreatePaymentMethodParams) (PaymentMethod, error) {
	row := q.db.QueryRow(ctx, createPaymentMethod,
		arg.Name,
		arg.PaymentTypeID,
		arg.UserID,
		arg.BudgetPersonID,
		arg.Color,
	)
	var i PaymentMethod
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.PaymentTypeID,
		&i.UserID,
		&i.IsActive,
		&i.BudgetPersonID,
		&i.Color,
		&i.PlaidAccountID,
		&i.Alias,
		&i.PlaidItemID,
	)
	return i, err
}

const createPaymentMethodFromPlaid = `-- name: CreatePaymentMethodFromPlaid :one
INSERT INTO payment_methods (name, payment_type_id, user_id, budget_person_id, plaid_account_id, plaid_item_id)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, name, payment_type_id, user_id, is_active, budget_person_id, color, plaid_account_id, alias, plaid_item_id
`

type CreatePaymentMethodFromPlaidParams struct {
	Name           string     `json:"name"`
	PaymentTypeID  *int32     `json:"payment_type_id"`
	UserID         *uuid.UUID `json:"user_id"`
	BudgetPersonID *int32     `json:"budget_person_id"`
	PlaidAccountID *string    `json:"plaid_account_id"`
	PlaidItemID    *uuid.UUID `json:"plaid_item_id"`
}

// Creates a payment method linked to a Plaid account. plaid_account_id is
// stored so the sync job can route imported transactions to the right
// method; plaid_item_id records which connection it came from, so
// RefreshPlaidAccounts can tell which payment methods to deactivate when an
// account is removed from that specific connection (a user may have
// multiple Plaid connections, so plaid_account_id alone isn't enough scope).
func (q *Queries) CreatePaymentMethodFromPlaid(ctx context.Context, arg CreatePaymentMethodFromPlaidParams) (PaymentMethod, error) {
	row := q.db.QueryRow(ctx, createPaymentMethodFromPlaid,
		arg.Name,
		arg.PaymentTypeID,
		arg.UserID,
		arg.BudgetPersonID,
		arg.PlaidAccountID,
		arg.PlaidItemID,
	)
	var i PaymentMethod
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.PaymentTypeID,
		&i.UserID,
		&i.IsActive,
		&i.BudgetPersonID,
		&i.Color,
		&i.PlaidAccountID,
		&i.Alias,
		&i.PlaidItemID,
	)
	return i, err
}

const createTransaction = `-- name: CreateTransaction :one
INSERT INTO transaction (
    name, amount, planned_amount, date, renewal_date,
    budget_period_id, category_id, payment_method_id, transaction_frequency_id, transaction_type_id,
    fixed_expense_id, carried_from_budget_period_id
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12)
RETURNING id, name, amount, planned_amount, date, renewal_date,
          budget_period_id, category_id, payment_method_id, transaction_frequency_id, transaction_type_id,
          is_paid, paid_date, fixed_expense_id, plaid_transaction_id, is_excluded, installment_fixed_expense_id, carried_from_budget_period_id,
       plaid_pfc_primary, plaid_pfc_detailed, plaid_reference_number, plaid_ppd_id
`

type CreateTransactionParams struct {
	Name                      *string        `json:"name"`
	Amount                    pgtype.Numeric `json:"amount"`
	PlannedAmount             pgtype.Numeric `json:"planned_amount"`
	Date                      pgtype.Date    `json:"date"`
	RenewalDate               pgtype.Date    `json:"renewal_date"`
	BudgetPeriodID            *uuid.UUID     `json:"budget_period_id"`
	CategoryID                *int32         `json:"category_id"`
	PaymentMethodID           *uuid.UUID     `json:"payment_method_id"`
	TransactionFrequencyID    *int32         `json:"transaction_frequency_id"`
	TransactionTypeID         *int32         `json:"transaction_type_id"`
	FixedExpenseID            *uuid.UUID     `json:"fixed_expense_id"`
	CarriedFromBudgetPeriodID *uuid.UUID     `json:"carried_from_budget_period_id"`
}

func (q *Queries) CreateTransaction(ctx context.Context, arg CreateTransactionParams) (Transaction, error) {
	row := q.db.QueryRow(ctx, createTransaction,
		arg.Name,
		arg.Amount,
		arg.PlannedAmount,
		arg.Date,
		arg.RenewalDate,
		arg.BudgetPeriodID,
		arg.CategoryID,
		arg.PaymentMethodID,
		arg.TransactionFrequencyID,
		arg.TransactionTypeID,
		arg.FixedExpenseID,
		arg.CarriedFromBudgetPeriodID,
	)
	var i Transaction
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Amount,
		&i.PlannedAmount,
		&i.Date,
		&i.RenewalDate,
		&i.BudgetPeriodID,
		&i.CategoryID,
		&i.PaymentMethodID,
		&i.TransactionFrequencyID,
		&i.TransactionTypeID,
		&i.IsPaid,
		&i.PaidDate,
		&i.FixedExpenseID,
		&i.PlaidTransactionID,
		&i.IsExcluded,
		&i.InstallmentFixedExpenseID,
		&i.CarriedFromBudgetPeriodID,
		&i.PlaidPfcPrimary,
		&i.PlaidPfcDetailed,
		&i.PlaidReferenceNumber,
		&i.PlaidPpdID,
	)
	return i, err
}

const createTransactionFromPlaid = `-- name: CreateTransactionFromPlaid :one

INSERT INTO transaction (
    name, amount, planned_amount, date, renewal_date,
    budget_period_id, category_id, payment_method_id, transaction_frequency_id, transaction_type_id,
    fixed_expense_id, plaid_transaction_id,
    plaid_pfc_primary, plaid_pfc_detailed, plaid_reference_number, plaid_ppd_id
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16)
RETURNING id, name, amount, planned_amount, date, renewal_date,
          budget_period_id, category_id, payment_method_id, transaction_frequency_id, transaction_type_id,
          is_paid, paid_date, fixed_expense_id, plaid_transaction_id, is_excluded, installment_fixed_expense_id, carried_from_budget_period_id,
       plaid_pfc_primary, plaid_pfc_detailed, plaid_reference_number, plaid_ppd_id
`

type CreateTransactionFromPlaidParams struct {
	Name                   *string        `json:"name"`
	Amount                 pgtype.Numeric `json:"amount"`
	PlannedAmount          pgtype.Numeric `json:"planned_amount"`
	Date                   pgtype.Date    `json:"date"`
	RenewalDate            pgtype.Date    `json:"renewal_date"`
	BudgetPeriodID         *uuid.UUID     `json:"budget_period_id"`
	CategoryID             *int32         `json:"category_id"`
	PaymentMethodID        *uuid.UUID     `json:"payment_method_id"`
	TransactionFrequencyID *int32         `json:"transaction_frequency_id"`
	TransactionTypeID      *int32         `json:"transaction_type_id"`
	FixedExpenseID         *uuid.UUID     `json:"fixed_expense_id"`
	PlaidTransactionID     *string        `json:"plaid_transaction_id"`
	PlaidPfcPrimary        *string        `json:"plaid_pfc_primary"`
	PlaidPfcDetailed       *string        `json:"plaid_pfc_detailed"`
	PlaidReferenceNumber   *string        `json:"plaid_reference_number"`
	PlaidPpdID             *string        `json:"plaid_ppd_id"`
}

// ── Plaid ─────────────────────────────────────────────────────────────────────
func (q *Queries) CreateTransactionFromPlaid(ctx context.Context, arg CreateTransactionFromPlaidParams) (Transaction, error) {
	row := q.db.QueryRow(ctx, createTransactionFromPlaid,
		arg.Name,
		arg.Amount,
		arg.PlannedAmount,
		arg.Date,
		arg.RenewalDate,
		arg.BudgetPeriodID,
		arg.CategoryID,
		arg.PaymentMethodID,
		arg.TransactionFrequencyID,
		arg.TransactionTypeID,
		arg.FixedExpenseID,
		arg.PlaidTransactionID,
		arg.PlaidPfcPrimary,
		arg.PlaidPfcDetailed,
		arg.PlaidReferenceNumber,
		arg.PlaidPpdID,
	)
	var i Transaction
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Amount,
		&i.PlannedAmount,
		&i.Date,
		&i.RenewalDate,
		&i.BudgetPeriodID,
		&i.CategoryID,
		&i.PaymentMethodID,
		&i.TransactionFrequencyID,
		&i.TransactionTypeID,
		&i.IsPaid,
		&i.PaidDate,
		&i.FixedExpenseID,
		&i.PlaidTransactionID,
		&i.IsExcluded,
		&i.InstallmentFixedExpenseID,
		&i.CarriedFromBudgetPeriodID,
		&i.PlaidPfcPrimary,
		&i.PlaidPfcDetailed,
		&i.PlaidReferenceNumber,
		&i.PlaidPpdID,
	)
	return i, err
}

const deactivatePaymentMethod = `-- name: DeactivatePaymentMethod :exec
WITH cleared_fixed_expenses AS (
    UPDATE fixed_expense SET payment_method_id = NULL
    WHERE payment_method_id = $1
), cleared_savings_sources AS (
    UPDATE savings_source SET payment_method_id = NULL
    WHERE payment_method_id = $1
)
UPDATE payment_methods
SET is_active = FALSE
WHERE payment_methods.id = $1
`

// Deactivates a payment method without reassigning its transactions —
// used when an account is removed from a Plaid connection via update mode.
// Unlike DeletePaymentMethodAndReassign, there's no user-chosen replacement
// here (this runs unattended, from the Plaid refresh that finds an account
// gone), so existing transactions simply keep pointing at the now-inactive
// method -- consistent with how soft-deleted categories/methods already work,
// and correct: they record what really happened.
//
// The recurring TEMPLATES are a different matter and are cleared. A
// fixed_expense still pointing here would respawn a bill onto the dead account
// every month, forever; a savings_source would keep scheduling transfers from
// it. NULL is the honest value -- "nobody knows which account pays this now" --
// and it is what the user can see and correct, where a reference to a
// deactivated method never appears in any picker.
func (q *Queries) DeactivatePaymentMethod(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deactivatePaymentMethod, id)
	return err
}

const deleteCategoryAndReassign = `-- name: DeleteCategoryAndReassign :exec
WITH moved_tx AS (
    UPDATE transaction SET category_id = $3
    WHERE category_id = $1
), moved_fe AS (
    UPDATE fixed_expense SET category_id = $3
    WHERE category_id = $1
)
UPDATE category
SET is_active = FALSE
WHERE category.id = $1 AND category.user_id = $2::uuid AND category.is_system = FALSE
`

type DeleteCategoryAndReassignParams struct {
	ID            int32     `json:"id"`
	UserID        uuid.UUID `json:"user_id"`
	ReplacementID *int32    `json:"replacement_id"`
}

// Reassigns all transactions and fixed-expense templates referencing this
// category to the replacement, then soft-deletes the category. Fixed expenses
// must be reassigned too, not just transactions: otherwise an orphaned
// template keeps the "deleted" category alive in ListCategoriesForBudget
// (which surfaces any category referenced by a fixed_expense row) and future
// transactions spawned from that template would carry the dead category_id.
// No budget scoping: categories are user-scoped so reassignment spans all periods.
func (q *Queries) DeleteCategoryAndReassign(ctx context.Context, arg DeleteCategoryAndReassignParams) error {
	_, err := q.db.Exec(ctx, deleteCategoryAndReassign, arg.ID, arg.UserID, arg.ReplacementID)
	return err
}

const deletePaymentMethodAndReassign = `-- name: DeletePaymentMethodAndReassign :exec
WITH moved_tx AS (
    UPDATE transaction SET payment_method_id = $2::uuid
    WHERE payment_method_id = $1::uuid
      AND budget_period_id IN (
        SELECT bp.id FROM budget_period bp WHERE bp.budget_profile_id = $3::uuid
      )
), moved_savings AS (
    UPDATE savings_source SET payment_method_id = $2::uuid
    WHERE payment_method_id = $1::uuid
      AND budget_profile_id = $3::uuid
), moved_fixed_expense AS (
    UPDATE fixed_expense SET payment_method_id = $2::uuid
    WHERE payment_method_id = $1::uuid
      AND budget_profile_id = $3::uuid
)
UPDATE payment_methods
SET is_active = FALSE
WHERE payment_methods.id = $1::uuid
`

type DeletePaymentMethodAndReassignParams struct {
	ID              uuid.UUID `json:"id"`
	ReplacementID   uuid.UUID `json:"replacement_id"`
	BudgetProfileID uuid.UUID `json:"budget_profile_id"`
}

// Reassigns all transactions, savings sources, and fixed-expense templates
// referencing this method, then soft-deletes. fixed_expense must be included
// alongside transaction/savings_source — otherwise every future period
// cycle spawned from an affected template keeps copying the now-inactive
// method's id onto its new transaction (see budget_profile_service.go's
// fixed-expense spawn logic), which renders blank once ListPaymentMethods
// filters it out as inactive.
func (q *Queries) DeletePaymentMethodAndReassign(ctx context.Context, arg DeletePaymentMethodAndReassignParams) error {
	_, err := q.db.Exec(ctx, deletePaymentMethodAndReassign, arg.ID, arg.ReplacementID, arg.BudgetProfileID)
	return err
}

const deletePaymentMethodsByIDs = `-- name: DeletePaymentMethodsByIDs :exec
DELETE FROM payment_methods WHERE id = ANY($1::uuid[])
`

// Run *after* the profile delete, never before: transaction.payment_method_id
// and savings_source.payment_method_id have no ON DELETE, so these rows cannot
// go until everything referencing them has already gone with the profile.
func (q *Queries) DeletePaymentMethodsByIDs(ctx context.Context, ids []uuid.UUID) error {
	_, err := q.db.Exec(ctx, deletePaymentMethodsByIDs, ids)
	return err
}

const deleteSavingsSourceTransactions = `-- name: DeleteSavingsSourceTransactions :exec
DELETE FROM transaction
WHERE budget_period_id IN (
    SELECT id FROM budget_period
    WHERE budget_profile_id = $1::uuid AND is_archived = FALSE
)
AND name = $2
AND payment_method_id = $3::uuid
AND category_id = $4
`

type DeleteSavingsSourceTransactionsParams struct {
	BudgetProfileID uuid.UUID `json:"budget_profile_id"`
	Name            *string   `json:"name"`
	PaymentMethodID uuid.UUID `json:"payment_method_id"`
	CategoryID      *int32    `json:"category_id"`
}

// Deletes auto-created savings transactions when a savings source is removed.
// Matches by name, payment method, and category within non-archived periods.
func (q *Queries) DeleteSavingsSourceTransactions(ctx context.Context, arg DeleteSavingsSourceTransactionsParams) error {
	_, err := q.db.Exec(ctx, deleteSavingsSourceTransactions,
		arg.BudgetProfileID,
		arg.Name,
		arg.PaymentMethodID,
		arg.CategoryID,
	)
	return err
}

const deleteTransaction = `-- name: DeleteTransaction :exec
DELETE FROM transaction
WHERE id = $1 AND budget_period_id = $2
`

type DeleteTransactionParams struct {
	ID             uuid.UUID  `json:"id"`
	BudgetPeriodID *uuid.UUID `json:"budget_period_id"`
}

func (q *Queries) DeleteTransaction(ctx context.Context, arg DeleteTransactionParams) error {
	_, err := q.db.Exec(ctx, deleteTransaction, arg.ID, arg.BudgetPeriodID)
	return err
}

const deleteTransactionByPlaidID = `-- name: DeleteTransactionByPlaidID :exec
DELETE FROM transaction
WHERE plaid_transaction_id = $1
`

func (q *Queries) DeleteTransactionByPlaidID(ctx context.Context, plaidTransactionID *string) error {
	_, err := q.db.Exec(ctx, deleteTransactionByPlaidID, plaidTransactionID)
	return err
}

const deleteTransactionsByFixedExpense = `-- name: DeleteTransactionsByFixedExpense :exec
DELETE FROM transaction WHERE fixed_expense_id = $1::uuid
`

func (q *Queries) DeleteTransactionsByFixedExpense(ctx context.Context, fixedExpenseID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteTransactionsByFixedExpense, fixedExpenseID)
	return err
}

const existsTransactionByPlaidID = `-- name: ExistsTransactionByPlaidID :one
SELECT EXISTS (
    SELECT 1 FROM transaction WHERE plaid_transaction_id = $1
) AS exists
`

func (q *Queries) ExistsTransactionByPlaidID(ctx context.Context, plaidTransactionID *string) (bool, error) {
	row := q.db.QueryRow(ctx, existsTransactionByPlaidID, plaidTransactionID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const getCategory = `-- name: GetCategory :one
SELECT id, name, type_id, is_system, user_id, color, system_key
FROM category
WHERE id = $1
LIMIT 1
`

type GetCategoryRow struct {
	ID        int32      `json:"id"`
	Name      string     `json:"name"`
	TypeID    *int32     `json:"type_id"`
	IsSystem  bool       `json:"is_system"`
	UserID    *uuid.UUID `json:"user_id"`
	Color     string     `json:"color"`
	SystemKey *string    `json:"system_key"`
}

func (q *Queries) GetCategory(ctx context.Context, id int32) (GetCategoryRow, error) {
	row := q.db.QueryRow(ctx, getCategory, id)
	var i GetCategoryRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.TypeID,
		&i.IsSystem,
		&i.UserID,
		&i.Color,
		&i.SystemKey,
	)
	return i, err
}

const getPaymentMethod = `-- name: GetPaymentMethod :one
SELECT id, name, payment_type_id, user_id, is_active, budget_person_id, color, plaid_account_id, alias, plaid_item_id
FROM payment_methods
WHERE id = $1
LIMIT 1
`

func (q *Queries) GetPaymentMethod(ctx context.Context, id uuid.UUID) (PaymentMethod, error) {
	row := q.db.QueryRow(ctx, getPaymentMethod, id)
	var i PaymentMethod
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.PaymentTypeID,
		&i.UserID,
		&i.IsActive,
		&i.BudgetPersonID,
		&i.Color,
		&i.PlaidAccountID,
		&i.Alias,
		&i.PlaidItemID,
	)
	return i, err
}

const getPaymentMethodByPlaidAccountID = `-- name: GetPaymentMethodByPlaidAccountID :one
SELECT id, name, payment_type_id, user_id, is_active, budget_person_id, color, plaid_account_id, alias, plaid_item_id
FROM payment_methods
WHERE plaid_account_id = $1 AND is_active = TRUE
LIMIT 1
`

func (q *Queries) GetPaymentMethodByPlaidAccountID(ctx context.Context, plaidAccountID *string) (PaymentMethod, error) {
	row := q.db.QueryRow(ctx, getPaymentMethodByPlaidAccountID, plaidAccountID)
	var i PaymentMethod
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.PaymentTypeID,
		&i.UserID,
		&i.IsActive,
		&i.BudgetPersonID,
		&i.Color,
		&i.PlaidAccountID,
		&i.Alias,
		&i.PlaidItemID,
	)
	return i, err
}

const getPaymentMethodByUserAndName = `-- name: GetPaymentMethodByUserAndName :one
SELECT id, name, payment_type_id, user_id, is_active, budget_person_id, color, plaid_account_id, alias, plaid_item_id
FROM payment_methods
WHERE user_id = $1 AND name = $2 AND is_active = TRUE
LIMIT 1
`

type GetPaymentMethodByUserAndNameParams struct {
	UserID *uuid.UUID `json:"user_id"`
	Name   string     `json:"name"`
}

func (q *Queries) GetPaymentMethodByUserAndName(ctx context.Context, arg GetPaymentMethodByUserAndNameParams) (PaymentMethod, error) {
	row := q.db.QueryRow(ctx, getPaymentMethodByUserAndName, arg.UserID, arg.Name)
	var i PaymentMethod
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.PaymentTypeID,
		&i.UserID,
		&i.IsActive,
		&i.BudgetPersonID,
		&i.Color,
		&i.PlaidAccountID,
		&i.Alias,
		&i.PlaidItemID,
	)
	return i, err
}

const getTransactionByID = `-- name: GetTransactionByID :one
SELECT id, name, amount, planned_amount, date, renewal_date,
       budget_period_id, category_id, payment_method_id, transaction_frequency_id, transaction_type_id,
       is_paid, paid_date, fixed_expense_id, plaid_transaction_id, is_excluded, installment_fixed_expense_id, carried_from_budget_period_id,
       plaid_pfc_primary, plaid_pfc_detailed, plaid_reference_number, plaid_ppd_id
FROM transaction
WHERE id = $1
LIMIT 1
`

func (q *Queries) GetTransactionByID(ctx context.Context, id uuid.UUID) (Transaction, error) {
	row := q.db.QueryRow(ctx, getTransactionByID, id)
	var i Transaction
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Amount,
		&i.PlannedAmount,
		&i.Date,
		&i.RenewalDate,
		&i.BudgetPeriodID,
		&i.CategoryID,
		&i.PaymentMethodID,
		&i.TransactionFrequencyID,
		&i.TransactionTypeID,
		&i.IsPaid,
		&i.PaidDate,
		&i.FixedExpenseID,
		&i.PlaidTransactionID,
		&i.IsExcluded,
		&i.InstallmentFixedExpenseID,
		&i.CarriedFromBudgetPeriodID,
		&i.PlaidPfcPrimary,
		&i.PlaidPfcDetailed,
		&i.PlaidReferenceNumber,
		&i.PlaidPpdID,
	)
	return i, err
}

const getTransactionByPlaidID = `-- name: GetTransactionByPlaidID :one
SELECT id, name, amount, planned_amount, date, renewal_date,
       budget_period_id, category_id, payment_method_id, transaction_frequency_id, transaction_type_id,
       is_paid, paid_date, fixed_expense_id, plaid_transaction_id, is_excluded, installment_fixed_expense_id, carried_from_budget_period_id,
       plaid_pfc_primary, plaid_pfc_detailed, plaid_reference_number, plaid_ppd_id
FROM transaction
WHERE plaid_transaction_id = $1
LIMIT 1
`

func (q *Queries) GetTransactionByPlaidID(ctx context.Context, plaidTransactionID *string) (Transaction, error) {
	row := q.db.QueryRow(ctx, getTransactionByPlaidID, plaidTransactionID)
	var i Transaction
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Amount,
		&i.PlannedAmount,
		&i.Date,
		&i.RenewalDate,
		&i.BudgetPeriodID,
		&i.CategoryID,
		&i.PaymentMethodID,
		&i.TransactionFrequencyID,
		&i.TransactionTypeID,
		&i.IsPaid,
		&i.PaidDate,
		&i.FixedExpenseID,
		&i.PlaidTransactionID,
		&i.IsExcluded,
		&i.InstallmentFixedExpenseID,
		&i.CarriedFromBudgetPeriodID,
		&i.PlaidPfcPrimary,
		&i.PlaidPfcDetailed,
		&i.PlaidReferenceNumber,
		&i.PlaidPpdID,
	)
	return i, err
}

const listActivePaymentMethodsByPlaidItem = `-- name: ListActivePaymentMethodsByPlaidItem :many
SELECT id, name, payment_type_id, user_id, is_active, budget_person_id, color, plaid_account_id, alias, plaid_item_id
FROM payment_methods
WHERE plaid_item_id = $1 AND is_active = TRUE
`

func (q *Queries) ListActivePaymentMethodsByPlaidItem(ctx context.Context, plaidItemID *uuid.UUID) ([]PaymentMethod, error) {
	rows, err := q.db.Query(ctx, listActivePaymentMethodsByPlaidItem, plaidItemID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PaymentMethod
	for rows.Next() {
		var i PaymentMethod
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.PaymentTypeID,
			&i.UserID,
			&i.IsActive,
			&i.BudgetPersonID,
			&i.Color,
			&i.PlaidAccountID,
			&i.Alias,
			&i.PlaidItemID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCategories = `-- name: ListCategories :many
SELECT id, name, type_id, is_system, user_id, color, system_key
FROM category
WHERE (user_id = $1::uuid AND is_active = TRUE) OR user_id IS NULL
ORDER BY name
`

type ListCategoriesRow struct {
	ID        int32      `json:"id"`
	Name      string     `json:"name"`
	TypeID    *int32     `json:"type_id"`
	IsSystem  bool       `json:"is_system"`
	UserID    *uuid.UUID `json:"user_id"`
	Color     string     `json:"color"`
	SystemKey *string    `json:"system_key"`
}

func (q *Queries) ListCategories(ctx context.Context, dollar_1 uuid.UUID) ([]ListCategoriesRow, error) {
	rows, err := q.db.Query(ctx, listCategories, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListCategoriesRow
	for rows.Next() {
		var i ListCategoriesRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.TypeID,
			&i.IsSystem,
			&i.UserID,
			&i.Color,
			&i.SystemKey,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCategoriesForBudget = `-- name: ListCategoriesForBudget :many
SELECT DISTINCT c.id, c.name, c.type_id, c.is_system, c.user_id, c.color, c.system_key
FROM category c
WHERE (
  (c.user_id = $1::uuid AND c.is_active = TRUE)
  OR c.user_id IS NULL
  OR c.id IN (
    SELECT DISTINCT t.category_id
    FROM transaction t
    JOIN budget_period bp ON t.budget_period_id = bp.id
    WHERE bp.budget_profile_id = $2::uuid
      AND t.category_id IS NOT NULL
  )
  OR c.id IN (
    SELECT DISTINCT fe.category_id
    FROM fixed_expense fe
    WHERE fe.budget_profile_id = $2::uuid
      AND fe.category_id IS NOT NULL
  )
)
ORDER BY c.name
`

type ListCategoriesForBudgetParams struct {
	UserID          uuid.UUID `json:"user_id"`
	BudgetProfileID uuid.UUID `json:"budget_profile_id"`
}

type ListCategoriesForBudgetRow struct {
	ID        int32      `json:"id"`
	Name      string     `json:"name"`
	TypeID    *int32     `json:"type_id"`
	IsSystem  bool       `json:"is_system"`
	UserID    *uuid.UUID `json:"user_id"`
	Color     string     `json:"color"`
	SystemKey *string    `json:"system_key"`
}

// Returns the same set as ListCategories but also includes categories referenced
// by transactions or fixed expenses in the given budget, so collaborators/viewers
// can see categories created by the budget owner.
func (q *Queries) ListCategoriesForBudget(ctx context.Context, arg ListCategoriesForBudgetParams) ([]ListCategoriesForBudgetRow, error) {
	rows, err := q.db.Query(ctx, listCategoriesForBudget, arg.UserID, arg.BudgetProfileID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListCategoriesForBudgetRow
	for rows.Next() {
		var i ListCategoriesForBudgetRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.TypeID,
			&i.IsSystem,
			&i.UserID,
			&i.Color,
			&i.SystemKey,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPaymentMethodIDsByBudgetProfile = `-- name: ListPaymentMethodIDsByBudgetProfile :many
SELECT id FROM payment_methods
WHERE budget_person_id IN (
    SELECT id FROM budget_to_profile_mapping WHERE budget_profile_id = $1::uuid
)
`

// Every payment method belonging to a budget, soft-deleted ones included.
//
// Deliberately not filtered on is_active, unlike ListPaymentMethods: this
// exists to clean up after a deleted budget profile, and an inactive method
// still holds a row and a foreign key. Ids only -- the caller does not need
// the rest, and reading them before the profile is deleted is the only
// moment the budget link still exists to read.
func (q *Queries) ListPaymentMethodIDsByBudgetProfile(ctx context.Context, dollar_1 uuid.UUID) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, listPaymentMethodIDsByBudgetProfile, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []uuid.UUID
	for rows.Next() {
		var id uuid.UUID
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPaymentMethods = `-- name: ListPaymentMethods :many
SELECT pm.id, pm.name, pm.payment_type_id, pm.user_id, pt.name AS type_name, pm.budget_person_id, pm.color, pm.alias
FROM payment_methods pm
LEFT JOIN payment_type pt ON pm.payment_type_id = pt.id
WHERE pm.budget_person_id IN (
    SELECT id FROM budget_to_profile_mapping WHERE budget_profile_id = $1::uuid
)
AND pm.is_active = TRUE
ORDER BY pm.name
`

type ListPaymentMethodsRow struct {
	ID             uuid.UUID  `json:"id"`
	Name           string     `json:"name"`
	PaymentTypeID  *int32     `json:"payment_type_id"`
	UserID         *uuid.UUID `json:"user_id"`
	TypeName       *string    `json:"type_name"`
	BudgetPersonID *int32     `json:"budget_person_id"`
	Color          string     `json:"color"`
	Alias          *string    `json:"alias"`
}

func (q *Queries) ListPaymentMethods(ctx context.Context, dollar_1 uuid.UUID) ([]ListPaymentMethodsRow, error) {
	rows, err := q.db.Query(ctx, listPaymentMethods, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPaymentMethodsRow
	for rows.Next() {
		var i ListPaymentMethodsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.PaymentTypeID,
			&i.UserID,
			&i.TypeName,
			&i.BudgetPersonID,
			&i.Color,
			&i.Alias,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSystemCategories = `-- name: ListSystemCategories :many
SELECT id, name, system_key FROM category WHERE is_system = TRUE ORDER BY name
`

type ListSystemCategoriesRow struct {
	ID        int32   `json:"id"`
	Name      string  `json:"name"`
	SystemKey *string `json:"system_key"`
}

// Returns all system (global) categories. Used by the Plaid sync job and the
// carryover step to resolve a system_key to a category ID without a user
// context. Ordered by name only for stable output; callers key on system_key.
func (q *Queries) ListSystemCategories(ctx context.Context) ([]ListSystemCategoriesRow, error) {
	rows, err := q.db.Query(ctx, listSystemCategories)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListSystemCategoriesRow
	for rows.Next() {
		var i ListSystemCategoriesRow
		if err := rows.Scan(&i.ID, &i.Name, &i.SystemKey); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTransactionFrequencies = `-- name: ListTransactionFrequencies :many
SELECT id, name FROM transaction_frequency ORDER BY id
`

func (q *Queries) ListTransactionFrequencies(ctx context.Context) ([]TransactionFrequency, error) {
	rows, err := q.db.Query(ctx, listTransactionFrequencies)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []TransactionFrequency
	for rows.Next() {
		var i TransactionFrequency
		if err := rows.Scan(&i.ID, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTransactionTypes = `-- name: ListTransactionTypes :many
SELECT id, name FROM transaction_type ORDER BY id
`

func (q *Queries) ListTransactionTypes(ctx context.Context) ([]TransactionType, error) {
	rows, err := q.db.Query(ctx, listTransactionTypes)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []TransactionType
	for rows.Next() {
		var i TransactionType
		if err := rows.Scan(&i.ID, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTransactions = `-- name: ListTransactions :many
SELECT id, name, amount, planned_amount, date, renewal_date,
       budget_period_id, category_id, payment_method_id, transaction_frequency_id, transaction_type_id,
       is_paid, paid_date, fixed_expense_id, plaid_transaction_id, is_excluded, installment_fixed_expense_id, carried_from_budget_period_id,
       plaid_pfc_primary, plaid_pfc_detailed, plaid_reference_number, plaid_ppd_id
FROM transaction
WHERE budget_period_id = $1::uuid
  AND ($2::int IS NULL OR category_id = $2)
  AND ($3::int IS NULL OR transaction_type_id = $3)
ORDER BY date DESC NULLS LAST
`

type ListTransactionsParams struct {
	BudgetPeriodID    uuid.UUID `json:"budget_period_id"`
	CategoryID        *int32    `json:"category_id"`
	TransactionTypeID *int32    `json:"transaction_type_id"`
}

// A confirmed review's imported transaction is intentionally NOT filtered out
// here — it stays visible and recoverable, same as an Income transaction.
// ConfirmTransactionReview excludes it from totals via is_excluded instead of
// hiding the row outright, so unmarking the matched fixed expense later never
// leaves it stranded/unrecoverable behind a review-status side channel.
func (q *Queries) ListTransactions(ctx context.Context, arg ListTransactionsParams) ([]Transaction, error) {
	rows, err := q.db.Query(ctx, listTransactions, arg.BudgetPeriodID, arg.CategoryID, arg.TransactionTypeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Transaction
	for rows.Next() {
		var i Transaction
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Amount,
			&i.PlannedAmount,
			&i.Date,
			&i.RenewalDate,
			&i.BudgetPeriodID,
			&i.CategoryID,
			&i.PaymentMethodID,
			&i.TransactionFrequencyID,
			&i.TransactionTypeID,
			&i.IsPaid,
			&i.PaidDate,
			&i.FixedExpenseID,
			&i.PlaidTransactionID,
			&i.IsExcluded,
			&i.InstallmentFixedExpenseID,
			&i.CarriedFromBudgetPeriodID,
			&i.PlaidPfcPrimary,
			&i.PlaidPfcDetailed,
			&i.PlaidReferenceNumber,
			&i.PlaidPpdID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTransactionsByFixedExpense = `-- name: ListTransactionsByFixedExpense :many
SELECT id, name, amount, planned_amount, date, renewal_date,
       budget_period_id, category_id, payment_method_id, transaction_frequency_id, transaction_type_id,
       is_paid, paid_date, fixed_expense_id, plaid_transaction_id, is_excluded, installment_fixed_expense_id, carried_from_budget_period_id,
       plaid_pfc_primary, plaid_pfc_detailed, plaid_reference_number, plaid_ppd_id
FROM transaction
WHERE fixed_expense_id = $1::uuid
`

// Every transaction spawned by a fixed-expense template, across all periods.
func (q *Queries) ListTransactionsByFixedExpense(ctx context.Context, fixedExpenseID uuid.UUID) ([]Transaction, error) {
	rows, err := q.db.Query(ctx, listTransactionsByFixedExpense, fixedExpenseID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Transaction
	for rows.Next() {
		var i Transaction
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Amount,
			&i.PlannedAmount,
			&i.Date,
			&i.RenewalDate,
			&i.BudgetPeriodID,
			&i.CategoryID,
			&i.PaymentMethodID,
			&i.TransactionFrequencyID,
			&i.TransactionTypeID,
			&i.IsPaid,
			&i.PaidDate,
			&i.FixedExpenseID,
			&i.PlaidTransactionID,
			&i.IsExcluded,
			&i.InstallmentFixedExpenseID,
			&i.CarriedFromBudgetPeriodID,
			&i.PlaidPfcPrimary,
			&i.PlaidPfcDetailed,
			&i.PlaidReferenceNumber,
			&i.PlaidPpdID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markTransactionAsPaid = `-- name: MarkTransactionAsPaid :one
UPDATE transaction
SET is_paid = TRUE,
    paid_date = $1::date,
    amount = $2
WHERE id = $3::uuid
  AND budget_period_id = $4::uuid
RETURNING id, name, amount, planned_amount, date, renewal_date,
          budget_period_id, category_id, payment_method_id, transaction_frequency_id, transaction_type_id,
          is_paid, paid_date, fixed_expense_id, plaid_transaction_id, is_excluded, installment_fixed_expense_id, carried_from_budget_period_id,
       plaid_pfc_primary, plaid_pfc_detailed, plaid_reference_number, plaid_ppd_id
`

type MarkTransactionAsPaidParams struct {
	PaidDate       pgtype.Date    `json:"paid_date"`
	Amount         pgtype.Numeric `json:"amount"`
	ID             uuid.UUID      `json:"id"`
	BudgetPeriodID uuid.UUID      `json:"budget_period_id"`
}

func (q *Queries) MarkTransactionAsPaid(ctx context.Context, arg MarkTransactionAsPaidParams) (Transaction, error) {
	row := q.db.QueryRow(ctx, markTransactionAsPaid,
		arg.PaidDate,
		arg.Amount,
		arg.ID,
		arg.BudgetPeriodID,
	)
	var i Transaction
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Amount,
		&i.PlannedAmount,
		&i.Date,
		&i.RenewalDate,
		&i.BudgetPeriodID,
		&i.CategoryID,
		&i.PaymentMethodID,
		&i.TransactionFrequencyID,
		&i.TransactionTypeID,
		&i.IsPaid,
		&i.PaidDate,
		&i.FixedExpenseID,
		&i.PlaidTransactionID,
		&i.IsExcluded,
		&i.InstallmentFixedExpenseID,
		&i.CarriedFromBudgetPeriodID,
		&i.PlaidPfcPrimary,
		&i.PlaidPfcDetailed,
		&i.PlaidReferenceNumber,
		&i.PlaidPpdID,
	)
	return i, err
}

const repointTransactionPlaidID = `-- name: RepointTransactionPlaidID :one
UPDATE transaction
SET plaid_transaction_id = $1,
    name = $2,
    amount = $3,
    date = $4
WHERE plaid_transaction_id = $5
RETURNING id, name, amount, planned_amount, date, renewal_date,
          budget_period_id, category_id, payment_method_id, transaction_frequency_id, transaction_type_id,
          is_paid, paid_date, fixed_expense_id, plaid_transaction_id, is_excluded, installment_fixed_expense_id, carried_from_budget_period_id,
          plaid_pfc_primary, plaid_pfc_detailed, plaid_reference_number, plaid_ppd_id
`

type RepointTransactionPlaidIDParams struct {
	NewPlaidTransactionID *string        `json:"new_plaid_transaction_id"`
	Name                  *string        `json:"name"`
	Amount                pgtype.Numeric `json:"amount"`
	Date                  pgtype.Date    `json:"date"`
	OldPlaidTransactionID *string        `json:"old_plaid_transaction_id"`
}

// Repoints a pending Plaid transaction onto the posted transaction that
// replaced it, in place. Some institutions represent settlement by moving
// the pending id into `removed` while the posted transaction arrives in
// `added` under a brand-new id, linked back only by pending_transaction_id
// (see plaidclient.Transaction.PendingTransactionID) — treating that as a
// delete-and-reinsert would cascade-delete any transaction_review pointing
// at this row (transaction_review.transaction_id is ON DELETE CASCADE) and
// silently drop the confirmed link to a fixed expense already marked paid.
// Updating in place instead means the row's id — and therefore the review's
// foreign key — never changes; only the Plaid-sourced fields are refreshed
// to the settled transaction's values. Runs before the removed-ids pass in
// the same sync, so DeleteTransactionByPlaidID finds nothing left to delete
// for the old id.
func (q *Queries) RepointTransactionPlaidID(ctx context.Context, arg RepointTransactionPlaidIDParams) (Transaction, error) {
	row := q.db.QueryRow(ctx, repointTransactionPlaidID,
		arg.NewPlaidTransactionID,
		arg.Name,
		arg.Amount,
		arg.Date,
		arg.OldPlaidTransactionID,
	)
	var i Transaction
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Amount,
		&i.PlannedAmount,
		&i.Date,
		&i.RenewalDate,
		&i.BudgetPeriodID,
		&i.CategoryID,
		&i.PaymentMethodID,
		&i.TransactionFrequencyID,
		&i.TransactionTypeID,
		&i.IsPaid,
		&i.PaidDate,
		&i.FixedExpenseID,
		&i.PlaidTransactionID,
		&i.IsExcluded,
		&i.InstallmentFixedExpenseID,
		&i.CarriedFromBudgetPeriodID,
		&i.PlaidPfcPrimary,
		&i.PlaidPfcDetailed,
		&i.PlaidReferenceNumber,
		&i.PlaidPpdID,
	)
	return i, err
}

const setTransactionExcluded = `-- name: SetTransactionExcluded :one
UPDATE transaction
SET is_excluded = $1::bool
WHERE id = $2::uuid
  AND budget_period_id = $3::uuid
RETURNING id, name, amount, planned_amount, date, renewal_date,
          budget_period_id, category_id, payment_method_id, transaction_frequency_id, transaction_type_id,
          is_paid, paid_date, fixed_expense_id, plaid_transaction_id, is_excluded, installment_fixed_expense_id, carried_from_budget_period_id,
       plaid_pfc_primary, plaid_pfc_detailed, plaid_reference_number, plaid_ppd_id
`

type SetTransactionExcludedParams struct {
	Excluded       bool      `json:"excluded"`
	ID             uuid.UUID `json:"id"`
	BudgetPeriodID uuid.UUID `json:"budget_period_id"`
}

func (q *Queries) SetTransactionExcluded(ctx context.Context, arg SetTransactionExcludedParams) (Transaction, error) {
	row := q.db.QueryRow(ctx, setTransactionExcluded, arg.Excluded, arg.ID, arg.BudgetPeriodID)
	var i Transaction
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Amount,
		&i.PlannedAmount,
		&i.Date,
		&i.RenewalDate,
		&i.BudgetPeriodID,
		&i.CategoryID,
		&i.PaymentMethodID,
		&i.TransactionFrequencyID,
		&i.TransactionTypeID,
		&i.IsPaid,
		&i.PaidDate,
		&i.FixedExpenseID,
		&i.PlaidTransactionID,
		&i.IsExcluded,
		&i.InstallmentFixedExpenseID,
		&i.CarriedFromBudgetPeriodID,
		&i.PlaidPfcPrimary,
		&i.PlaidPfcDetailed,
		&i.PlaidReferenceNumber,
		&i.PlaidPpdID,
	)
	return i, err
}

const setTransactionInstallmentPlan = `-- name: SetTransactionInstallmentPlan :one
UPDATE transaction
SET is_excluded = TRUE,
    installment_fixed_expense_id = $1::uuid
WHERE id = $2::uuid
  AND budget_period_id = $3::uuid
RETURNING id, name, amount, planned_amount, date, renewal_date,
          budget_period_id, category_id, payment_method_id, transaction_frequency_id, transaction_type_id,
          is_paid, paid_date, fixed_expense_id, plaid_transaction_id, is_excluded, installment_fixed_expense_id, carried_from_budget_period_id,
       plaid_pfc_primary, plaid_pfc_detailed, plaid_reference_number, plaid_ppd_id
`

type SetTransactionInstallmentPlanParams struct {
	InstallmentFixedExpenseID uuid.UUID `json:"installment_fixed_expense_id"`
	ID                        uuid.UUID `json:"id"`
	BudgetPeriodID            uuid.UUID `json:"budget_period_id"`
}

// Converts a transaction into an installment plan: excludes it from totals and
// records which plan it became. Both in one statement so a transaction can
// never be excluded without the plan that explains why (issue #54).
// Deliberately not scoped by budget_period_id's archived flag — converting a
// past purchase into installments is explicitly allowed on an archived period.
func (q *Queries) SetTransactionInstallmentPlan(ctx context.Context, arg SetTransactionInstallmentPlanParams) (Transaction, error) {
	row := q.db.QueryRow(ctx, setTransactionInstallmentPlan, arg.InstallmentFixedExpenseID, arg.ID, arg.BudgetPeriodID)
	var i Transaction
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Amount,
		&i.PlannedAmount,
		&i.Date,
		&i.RenewalDate,
		&i.BudgetPeriodID,
		&i.CategoryID,
		&i.PaymentMethodID,
		&i.TransactionFrequencyID,
		&i.TransactionTypeID,
		&i.IsPaid,
		&i.PaidDate,
		&i.FixedExpenseID,
		&i.PlaidTransactionID,
		&i.IsExcluded,
		&i.InstallmentFixedExpenseID,
		&i.CarriedFromBudgetPeriodID,
		&i.PlaidPfcPrimary,
		&i.PlaidPfcDetailed,
		&i.PlaidReferenceNumber,
		&i.PlaidPpdID,
	)
	return i, err
}

const unmarkTransactionAsPaid = `-- name: UnmarkTransactionAsPaid :one
UPDATE transaction
SET is_paid = FALSE,
    paid_date = NULL,
    amount = planned_amount
WHERE id = $1::uuid
  AND budget_period_id = $2::uuid
RETURNING id, name, amount, planned_amount, date, renewal_date,
          budget_period_id, category_id, payment_method_id, transaction_frequency_id, transaction_type_id,
          is_paid, paid_date, fixed_expense_id, plaid_transaction_id, is_excluded, installment_fixed_expense_id, carried_from_budget_period_id,
       plaid_pfc_primary, plaid_pfc_detailed, plaid_reference_number, plaid_ppd_id
`

type UnmarkTransactionAsPaidParams struct {
	ID             uuid.UUID `json:"id"`
	BudgetPeriodID uuid.UUID `json:"budget_period_id"`
}

func (q *Queries) UnmarkTransactionAsPaid(ctx context.Context, arg UnmarkTransactionAsPaidParams) (Transaction, error) {
	row := q.db.QueryRow(ctx, unmarkTransactionAsPaid, arg.ID, arg.BudgetPeriodID)
	var i Transaction
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Amount,
		&i.PlannedAmount,
		&i.Date,
		&i.RenewalDate,
		&i.BudgetPeriodID,
		&i.CategoryID,
		&i.PaymentMethodID,
		&i.TransactionFrequencyID,
		&i.TransactionTypeID,
		&i.IsPaid,
		&i.PaidDate,
		&i.FixedExpenseID,
		&i.PlaidTransactionID,
		&i.IsExcluded,
		&i.InstallmentFixedExpenseID,
		&i.CarriedFromBudgetPeriodID,
		&i.PlaidPfcPrimary,
		&i.PlaidPfcDetailed,
		&i.PlaidReferenceNumber,
		&i.PlaidPpdID,
	)
	return i, err
}

const updateCategory = `-- name: UpdateCategory :one
UPDATE category
SET name = $1, color = $2
WHERE id = $3 AND user_id = $4::uuid AND is_system = FALSE
RETURNING id, name, type_id, is_system, user_id, color, system_key
`

type UpdateCategoryParams struct {
	Name   string    `json:"name"`
	Color  string    `json:"color"`
	ID     int32     `json:"id"`
	UserID uuid.UUID `json:"user_id"`
}

type UpdateCategoryRow struct {
	ID        int32      `json:"id"`
	Name      string     `json:"name"`
	TypeID    *int32     `json:"type_id"`
	IsSystem  bool       `json:"is_system"`
	UserID    *uuid.UUID `json:"user_id"`
	Color     string     `json:"color"`
	SystemKey *string    `json:"system_key"`
}

func (q *Queries) UpdateCategory(ctx context.Context, arg UpdateCategoryParams) (UpdateCategoryRow, error) {
	row := q.db.QueryRow(ctx, updateCategory,
		arg.Name,
		arg.Color,
		arg.ID,
		arg.UserID,
	)
	var i UpdateCategoryRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.TypeID,
		&i.IsSystem,
		&i.UserID,
		&i.Color,
		&i.SystemKey,
	)
	return i, err
}

const updatePaymentMethod = `-- name: UpdatePaymentMethod :one
UPDATE payment_methods
SET name = $1, color = $2, alias = $3
WHERE payment_methods.id = $4
RETURNING id, name, payment_type_id, user_id, is_active, budget_person_id, color, plaid_account_id, alias, plaid_item_id
`

type UpdatePaymentMethodParams struct {
	Name  string    `json:"name"`
	Color string    `json:"color"`
	Alias *string   `json:"alias"`
	ID    uuid.UUID `json:"id"`
}

func (q *Queries) UpdatePaymentMethod(ctx context.Context, arg UpdatePaymentMethodParams) (PaymentMethod, error) {
	row := q.db.QueryRow(ctx, updatePaymentMethod,
		arg.Name,
		arg.Color,
		arg.Alias,
		arg.ID,
	)
	var i PaymentMethod
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.PaymentTypeID,
		&i.UserID,
		&i.IsActive,
		&i.BudgetPersonID,
		&i.Color,
		&i.PlaidAccountID,
		&i.Alias,
		&i.PlaidItemID,
	)
	return i, err
}

const updatePaymentMethodPlaidAccountID = `-- name: UpdatePaymentMethodPlaidAccountID :exec
UPDATE payment_methods
SET plaid_account_id = $1
WHERE id = $2
`

type UpdatePaymentMethodPlaidAccountIDParams struct {
	PlaidAccountID *string   `json:"plaid_account_id"`
	ID             uuid.UUID `json:"id"`
}

func (q *Queries) UpdatePaymentMethodPlaidAccountID(ctx context.Context, arg UpdatePaymentMethodPlaidAccountIDParams) error {
	_, err := q.db.Exec(ctx, updatePaymentMethodPlaidAccountID, arg.PlaidAccountID, arg.ID)
	return err
}

const updateSystemCategoryColor = `-- name: UpdateSystemCategoryColor :one
UPDATE category
SET color = $1
WHERE id = $2 AND is_system = TRUE
RETURNING id, name, type_id, is_system, user_id, color, system_key
`

type UpdateSystemCategoryColorParams struct {
	Color string `json:"color"`
	ID    int32  `json:"id"`
}

type UpdateSystemCategoryColorRow struct {
	ID        int32      `json:"id"`
	Name      string     `json:"name"`
	TypeID    *int32     `json:"type_id"`
	IsSystem  bool       `json:"is_system"`
	UserID    *uuid.UUID `json:"user_id"`
	Color     string     `json:"color"`
	SystemKey *string    `json:"system_key"`
}

func (q *Queries) UpdateSystemCategoryColor(ctx context.Context, arg UpdateSystemCategoryColorParams) (UpdateSystemCategoryColorRow, error) {
	row := q.db.QueryRow(ctx, updateSystemCategoryColor, arg.Color, arg.ID)
	var i UpdateSystemCategoryColorRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.TypeID,
		&i.IsSystem,
		&i.UserID,
		&i.Color,
		&i.SystemKey,
	)
	return i, err
}

const updateTransaction = `-- name: UpdateTransaction :one
UPDATE transaction
SET name = $2, amount = $3, planned_amount = $4, date = $5,
    category_id = $6, payment_method_id = $7, transaction_frequency_id = $8, transaction_type_id = $9
WHERE id = $1
RETURNING id, name, amount, planned_amount, date, renewal_date,
          budget_period_id, category_id, payment_method_id, transaction_frequency_id, transaction_type_id,
          is_paid, paid_date, fixed_expense_id, plaid_transaction_id, is_excluded, installment_fixed_expense_id, carried_from_budget_period_id,
       plaid_pfc_primary, plaid_pfc_detailed, plaid_reference_number, plaid_ppd_id
`

type UpdateTransactionParams struct {
	ID                     uuid.UUID      `json:"id"`
	Name                   *string        `json:"name"`
	Amount                 pgtype.Numeric `json:"amount"`
	PlannedAmount          pgtype.Numeric `json:"planned_amount"`
	Date                   pgtype.Date    `json:"date"`
	CategoryID             *int32         `json:"category_id"`
	PaymentMethodID        *uuid.UUID     `json:"payment_method_id"`
	TransactionFrequencyID *int32         `json:"transaction_frequency_id"`
	TransactionTypeID      *int32         `json:"transaction_type_id"`
}

func (q *Queries) UpdateTransaction(ctx context.Context, arg UpdateTransactionParams) (Transaction, error) {
	row := q.db.QueryRow(ctx, updateTransaction,
		arg.ID,
		arg.Name,
		arg.Amount,
		arg.PlannedAmount,
		arg.Date,
		arg.CategoryID,
		arg.PaymentMethodID,
		arg.TransactionFrequencyID,
		arg.TransactionTypeID,
	)
	var i Transaction
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Amount,
		&i.PlannedAmount,
		&i.Date,
		&i.RenewalDate,
		&i.BudgetPeriodID,
		&i.CategoryID,
		&i.PaymentMethodID,
		&i.TransactionFrequencyID,
		&i.TransactionTypeID,
		&i.IsPaid,
		&i.PaidDate,
		&i.FixedExpenseID,
		&i.PlaidTransactionID,
		&i.IsExcluded,
		&i.InstallmentFixedExpenseID,
		&i.CarriedFromBudgetPeriodID,
		&i.PlaidPfcPrimary,
		&i.PlaidPfcDetailed,
		&i.PlaidReferenceNumber,
		&i.PlaidPpdID,
	)
	return i, err
}

const updateTransactionFromPlaid = `-- name: UpdateTransactionFromPlaid :exec
UPDATE transaction
SET name = $2, amount = $3
WHERE plaid_transaction_id = $1
`

type UpdateTransactionFromPlaidParams struct {
	PlaidTransactionID *string        `json:"plaid_transaction_id"`
	Name               *string        `json:"name"`
	Amount             pgtype.Numeric `json:"amount"`
}

// Updates name and amount for a Plaid-imported transaction.
func (q *Queries) UpdateTransactionFromPlaid(ctx context.Context, arg UpdateTransactionFromPlaidParams) error {
	_, err := q.db.Exec(ctx, updateTransactionFromPlaid, arg.PlaidTransactionID, arg.Name, arg.Amount)
	return err
}
