// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: user.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createOAuthAccount = `-- name: CreateOAuthAccount :one
INSERT INTO oauth_account (user_id, oauth_name, account_id, account_email, refresh_token)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, user_id, oauth_name, account_id, account_email, refresh_token
`

type CreateOAuthAccountParams struct {
	UserID       uuid.UUID `json:"user_id"`
	OauthName    string    `json:"oauth_name"`
	AccountID    string    `json:"account_id"`
	AccountEmail string    `json:"account_email"`
	RefreshToken *string   `json:"refresh_token"`
}

func (q *Queries) CreateOAuthAccount(ctx context.Context, arg CreateOAuthAccountParams) (OauthAccount, error) {
	row := q.db.QueryRow(ctx, createOAuthAccount,
		arg.UserID,
		arg.OauthName,
		arg.AccountID,
		arg.AccountEmail,
		arg.RefreshToken,
	)
	var i OauthAccount
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.OauthName,
		&i.AccountID,
		&i.AccountEmail,
		&i.RefreshToken,
	)
	return i, err
}

const createUser = `-- name: CreateUser :one
INSERT INTO users (email, hashed_password, first_name, last_name, country_code, state_code, language, currency)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, email, hashed_password, first_name, last_name, is_active, is_superuser, is_verified, created_at,
          country_code, state_code, filing_status, tax_payment_frequency, language, currency,
          email_verification_token, email_verification_expires_at, email_verification_last_sent_at,
          status, active_until, plan, account_type
`

type CreateUserParams struct {
	Email          string  `json:"email"`
	HashedPassword *string `json:"hashed_password"`
	FirstName      *string `json:"first_name"`
	LastName       *string `json:"last_name"`
	CountryCode    *string `json:"country_code"`
	StateCode      *string `json:"state_code"`
	Language       string  `json:"language"`
	Currency       string  `json:"currency"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.Email,
		arg.HashedPassword,
		arg.FirstName,
		arg.LastName,
		arg.CountryCode,
		arg.StateCode,
		arg.Language,
		arg.Currency,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.HashedPassword,
		&i.FirstName,
		&i.LastName,
		&i.IsActive,
		&i.IsSuperuser,
		&i.IsVerified,
		&i.CreatedAt,
		&i.CountryCode,
		&i.StateCode,
		&i.FilingStatus,
		&i.TaxPaymentFrequency,
		&i.Language,
		&i.Currency,
		&i.EmailVerificationToken,
		&i.EmailVerificationExpiresAt,
		&i.EmailVerificationLastSentAt,
		&i.Status,
		&i.ActiveUntil,
		&i.Plan,
		&i.AccountType,
	)
	return i, err
}

const deleteUser = `-- name: DeleteUser :exec
DELETE FROM users
WHERE id = $1
`

func (q *Queries) DeleteUser(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteUser, id)
	return err
}

const getOAuthAccount = `-- name: GetOAuthAccount :one
SELECT id, user_id, oauth_name, account_id, account_email, refresh_token
FROM oauth_account
WHERE oauth_name = $1 AND account_id = $2
LIMIT 1
`

type GetOAuthAccountParams struct {
	OauthName string `json:"oauth_name"`
	AccountID string `json:"account_id"`
}

func (q *Queries) GetOAuthAccount(ctx context.Context, arg GetOAuthAccountParams) (OauthAccount, error) {
	row := q.db.QueryRow(ctx, getOAuthAccount, arg.OauthName, arg.AccountID)
	var i OauthAccount
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.OauthName,
		&i.AccountID,
		&i.AccountEmail,
		&i.RefreshToken,
	)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, email, hashed_password, first_name, last_name, is_active, is_superuser, is_verified, created_at,
       country_code, state_code, filing_status, tax_payment_frequency, language, currency,
       email_verification_token, email_verification_expires_at, email_verification_last_sent_at,
       status, active_until, plan, account_type
FROM users
WHERE email = $1
LIMIT 1
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.HashedPassword,
		&i.FirstName,
		&i.LastName,
		&i.IsActive,
		&i.IsSuperuser,
		&i.IsVerified,
		&i.CreatedAt,
		&i.CountryCode,
		&i.StateCode,
		&i.FilingStatus,
		&i.TaxPaymentFrequency,
		&i.Language,
		&i.Currency,
		&i.EmailVerificationToken,
		&i.EmailVerificationExpiresAt,
		&i.EmailVerificationLastSentAt,
		&i.Status,
		&i.ActiveUntil,
		&i.Plan,
		&i.AccountType,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, email, hashed_password, first_name, last_name, is_active, is_superuser, is_verified, created_at,
       country_code, state_code, filing_status, tax_payment_frequency, language, currency,
       email_verification_token, email_verification_expires_at, email_verification_last_sent_at,
       status, active_until, plan, account_type
FROM users
WHERE id = $1
LIMIT 1
`

func (q *Queries) GetUserByID(ctx context.Context, id uuid.UUID) (User, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.HashedPassword,
		&i.FirstName,
		&i.LastName,
		&i.IsActive,
		&i.IsSuperuser,
		&i.IsVerified,
		&i.CreatedAt,
		&i.CountryCode,
		&i.StateCode,
		&i.FilingStatus,
		&i.TaxPaymentFrequency,
		&i.Language,
		&i.Currency,
		&i.EmailVerificationToken,
		&i.EmailVerificationExpiresAt,
		&i.EmailVerificationLastSentAt,
		&i.Status,
		&i.ActiveUntil,
		&i.Plan,
		&i.AccountType,
	)
	return i, err
}

const getUserByVerificationToken = `-- name: GetUserByVerificationToken :one
SELECT id, email, hashed_password, first_name, last_name, is_active, is_superuser, is_verified, created_at,
       country_code, state_code, filing_status, tax_payment_frequency, language, currency,
       email_verification_token, email_verification_expires_at, email_verification_last_sent_at,
       status, active_until, plan, account_type
FROM users
WHERE email_verification_token = $1
LIMIT 1
`

func (q *Queries) GetUserByVerificationToken(ctx context.Context, token *uuid.UUID) (User, error) {
	row := q.db.QueryRow(ctx, getUserByVerificationToken, token)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.HashedPassword,
		&i.FirstName,
		&i.LastName,
		&i.IsActive,
		&i.IsSuperuser,
		&i.IsVerified,
		&i.CreatedAt,
		&i.CountryCode,
		&i.StateCode,
		&i.FilingStatus,
		&i.TaxPaymentFrequency,
		&i.Language,
		&i.Currency,
		&i.EmailVerificationToken,
		&i.EmailVerificationExpiresAt,
		&i.EmailVerificationLastSentAt,
		&i.Status,
		&i.ActiveUntil,
		&i.Plan,
		&i.AccountType,
	)
	return i, err
}

const listCountryFeatures = `-- name: ListCountryFeatures :many
SELECT country_code, feature_name, is_enabled
FROM country_features
ORDER BY country_code, feature_name
`

func (q *Queries) ListCountryFeatures(ctx context.Context) ([]CountryFeature, error) {
	rows, err := q.db.Query(ctx, listCountryFeatures)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CountryFeature
	for rows.Next() {
		var i CountryFeature
		if err := rows.Scan(&i.CountryCode, &i.FeatureName, &i.IsEnabled); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEnabledCountries = `-- name: ListEnabledCountries :many
SELECT code, name, is_enabled
FROM countries
WHERE is_enabled = TRUE
ORDER BY name
`

type ListEnabledCountriesRow struct {
	Code      string `json:"code"`
	Name      string `json:"name"`
	IsEnabled bool   `json:"is_enabled"`
}

func (q *Queries) ListEnabledCountries(ctx context.Context) ([]ListEnabledCountriesRow, error) {
	rows, err := q.db.Query(ctx, listEnabledCountries)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListEnabledCountriesRow
	for rows.Next() {
		var i ListEnabledCountriesRow
		if err := rows.Scan(&i.Code, &i.Name, &i.IsEnabled); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOAuthAccountsByUser = `-- name: ListOAuthAccountsByUser :many
SELECT id, user_id, oauth_name, account_id, account_email, refresh_token
FROM oauth_account
WHERE user_id = $1
ORDER BY oauth_name
`

func (q *Queries) ListOAuthAccountsByUser(ctx context.Context, userID uuid.UUID) ([]OauthAccount, error) {
	rows, err := q.db.Query(ctx, listOAuthAccountsByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []OauthAccount
	for rows.Next() {
		var i OauthAccount
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.OauthName,
			&i.AccountID,
			&i.AccountEmail,
			&i.RefreshToken,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTestAccounts = `-- name: ListTestAccounts :many
SELECT id, email
FROM users
WHERE account_type = 'test'
ORDER BY email
`

type ListTestAccountsRow struct {
	ID    uuid.UUID `json:"id"`
	Email string    `json:"email"`
}

// Backs the startup warning: accounts exempt from the email-verification gate
// should never sit in production unnoticed.
func (q *Queries) ListTestAccounts(ctx context.Context) ([]ListTestAccountsRow, error) {
	rows, err := q.db.Query(ctx, listTestAccounts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListTestAccountsRow
	for rows.Next() {
		var i ListTestAccountsRow
		if err := rows.Scan(&i.ID, &i.Email); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markUserVerified = `-- name: MarkUserVerified :exec
UPDATE users
SET is_verified = TRUE,
    email_verification_token = NULL,
    email_verification_expires_at = NULL
WHERE id = $1
`

func (q *Queries) MarkUserVerified(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, markUserVerified, id)
	return err
}

const setEmailVerificationToken = `-- name: SetEmailVerificationToken :one
UPDATE users
SET email_verification_token = $1,
    email_verification_expires_at = $2,
    email_verification_last_sent_at = $3
WHERE id = $4
RETURNING id, email, hashed_password, first_name, last_name, is_active, is_superuser, is_verified, created_at,
          country_code, state_code, filing_status, tax_payment_frequency, language, currency,
          email_verification_token, email_verification_expires_at, email_verification_last_sent_at,
          status, active_until, plan, account_type
`

type SetEmailVerificationTokenParams struct {
	Token      *uuid.UUID         `json:"token"`
	ExpiresAt  pgtype.Timestamptz `json:"expires_at"`
	LastSentAt pgtype.Timestamptz `json:"last_sent_at"`
	ID         uuid.UUID          `json:"id"`
}

func (q *Queries) SetEmailVerificationToken(ctx context.Context, arg SetEmailVerificationTokenParams) (User, error) {
	row := q.db.QueryRow(ctx, setEmailVerificationToken,
		arg.Token,
		arg.ExpiresAt,
		arg.LastSentAt,
		arg.ID,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.HashedPassword,
		&i.FirstName,
		&i.LastName,
		&i.IsActive,
		&i.IsSuperuser,
		&i.IsVerified,
		&i.CreatedAt,
		&i.CountryCode,
		&i.StateCode,
		&i.FilingStatus,
		&i.TaxPaymentFrequency,
		&i.Language,
		&i.Currency,
		&i.EmailVerificationToken,
		&i.EmailVerificationExpiresAt,
		&i.EmailVerificationLastSentAt,
		&i.Status,
		&i.ActiveUntil,
		&i.Plan,
		&i.AccountType,
	)
	return i, err
}

const softDeleteUser = `-- name: SoftDeleteUser :exec
UPDATE users
SET status       = 'disabled',
    is_active    = FALSE,
    active_until = NOW() + INTERVAL '30 days'
WHERE id = $1
`

func (q *Queries) SoftDeleteUser(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, softDeleteUser, id)
	return err
}

const updateOAuthAccountRefreshToken = `-- name: UpdateOAuthAccountRefreshToken :exec
UPDATE oauth_account
SET refresh_token = $2
WHERE id = $1
`

type UpdateOAuthAccountRefreshTokenParams struct {
	ID           uuid.UUID `json:"id"`
	RefreshToken *string   `json:"refresh_token"`
}

func (q *Queries) UpdateOAuthAccountRefreshToken(ctx context.Context, arg UpdateOAuthAccountRefreshTokenParams) error {
	_, err := q.db.Exec(ctx, updateOAuthAccountRefreshToken, arg.ID, arg.RefreshToken)
	return err
}

const updateUser = `-- name: UpdateUser :one
UPDATE users
SET first_name            = $1,
    last_name             = $2,
    country_code          = $3,
    state_code            = $4,
    filing_status         = $5,
    tax_payment_frequency = $6,
    language              = $7,
    currency              = $8
WHERE id = $9
RETURNING id, email, hashed_password, first_name, last_name, is_active, is_superuser, is_verified, created_at,
          country_code, state_code, filing_status, tax_payment_frequency, language, currency,
          email_verification_token, email_verification_expires_at, email_verification_last_sent_at,
          status, active_until, plan, account_type
`

type UpdateUserParams struct {
	FirstName           *string   `json:"first_name"`
	LastName            *string   `json:"last_name"`
	CountryCode         *string   `json:"country_code"`
	StateCode           *string   `json:"state_code"`
	FilingStatus        string    `json:"filing_status"`
	TaxPaymentFrequency int32     `json:"tax_payment_frequency"`
	Language            string    `json:"language"`
	Currency            string    `json:"currency"`
	ID                  uuid.UUID `json:"id"`
}

func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, updateUser,
		arg.FirstName,
		arg.LastName,
		arg.CountryCode,
		arg.StateCode,
		arg.FilingStatus,
		arg.TaxPaymentFrequency,
		arg.Language,
		arg.Currency,
		arg.ID,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.HashedPassword,
		&i.FirstName,
		&i.LastName,
		&i.IsActive,
		&i.IsSuperuser,
		&i.IsVerified,
		&i.CreatedAt,
		&i.CountryCode,
		&i.StateCode,
		&i.FilingStatus,
		&i.TaxPaymentFrequency,
		&i.Language,
		&i.Currency,
		&i.EmailVerificationToken,
		&i.EmailVerificationExpiresAt,
		&i.EmailVerificationLastSentAt,
		&i.Status,
		&i.ActiveUntil,
		&i.Plan,
		&i.AccountType,
	)
	return i, err
}

const updateUserEmail = `-- name: UpdateUserEmail :one
UPDATE users
SET email       = $1,
    is_verified = FALSE
WHERE id = $2
RETURNING id, email, hashed_password, first_name, last_name, is_active, is_superuser, is_verified, created_at,
          country_code, state_code, filing_status, tax_payment_frequency, language, currency,
          email_verification_token, email_verification_expires_at, email_verification_last_sent_at,
          status, active_until, plan, account_type
`

type UpdateUserEmailParams struct {
	Email string    `json:"email"`
	ID    uuid.UUID `json:"id"`
}

// Clearing is_verified is the point, not a side effect: the new address is
// unproven until its own verification link is redeemed.
func (q *Queries) UpdateUserEmail(ctx context.Context, arg UpdateUserEmailParams) (User, error) {
	row := q.db.QueryRow(ctx, updateUserEmail, arg.Email, arg.ID)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.HashedPassword,
		&i.FirstName,
		&i.LastName,
		&i.IsActive,
		&i.IsSuperuser,
		&i.IsVerified,
		&i.CreatedAt,
		&i.CountryCode,
		&i.StateCode,
		&i.FilingStatus,
		&i.TaxPaymentFrequency,
		&i.Language,
		&i.Currency,
		&i.EmailVerificationToken,
		&i.EmailVerificationExpiresAt,
		&i.EmailVerificationLastSentAt,
		&i.Status,
		&i.ActiveUntil,
		&i.Plan,
		&i.AccountType,
	)
	return i, err
}

const updateUserPassword = `-- name: UpdateUserPassword :exec
UPDATE users
SET hashed_password = $2
WHERE id = $1
`

type UpdateUserPasswordParams struct {
	ID             uuid.UUID `json:"id"`
	HashedPassword *string   `json:"hashed_password"`
}

func (q *Queries) UpdateUserPassword(ctx context.Context, arg UpdateUserPasswordParams) error {
	_, err := q.db.Exec(ctx, updateUserPassword, arg.ID, arg.HashedPassword)
	return err
}
