// Code generated by sqlc. DO NOT EDIT.
// This file will be regenerated by `sqlc generate`.

package db

import (
	"context"

	"github.com/google/uuid"
)

const getUserByID = `SELECT id, email, hashed_password, first_name, last_name, is_active, is_superuser, is_verified, created_at FROM users WHERE id = $1 LIMIT 1`

func (q *Queries) GetUserByID(ctx context.Context, id uuid.UUID) (User, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var u User
	err := row.Scan(&u.ID, &u.Email, &u.HashedPassword, &u.FirstName, &u.LastName,
		&u.IsActive, &u.IsSuperuser, &u.IsVerified, &u.CreatedAt)
	return u, err
}

const getUserByEmail = `SELECT id, email, hashed_password, first_name, last_name, is_active, is_superuser, is_verified, created_at FROM users WHERE email = $1 LIMIT 1`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var u User
	err := row.Scan(&u.ID, &u.Email, &u.HashedPassword, &u.FirstName, &u.LastName,
		&u.IsActive, &u.IsSuperuser, &u.IsVerified, &u.CreatedAt)
	return u, err
}

type CreateUserParams struct {
	Email          string
	HashedPassword *string
	FirstName      *string
	LastName       *string
}

const createUser = `INSERT INTO users (email, hashed_password, first_name, last_name) VALUES ($1, $2, $3, $4) RETURNING id, email, hashed_password, first_name, last_name, is_active, is_superuser, is_verified, created_at`

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser, arg.Email, arg.HashedPassword, arg.FirstName, arg.LastName)
	var u User
	err := row.Scan(&u.ID, &u.Email, &u.HashedPassword, &u.FirstName, &u.LastName,
		&u.IsActive, &u.IsSuperuser, &u.IsVerified, &u.CreatedAt)
	return u, err
}

type UpdateUserParams struct {
	ID        uuid.UUID
	FirstName *string
	LastName  *string
}

const updateUser = `UPDATE users SET first_name = $2, last_name = $3 WHERE id = $1 RETURNING id, email, hashed_password, first_name, last_name, is_active, is_superuser, is_verified, created_at`

func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, updateUser, arg.ID, arg.FirstName, arg.LastName)
	var u User
	err := row.Scan(&u.ID, &u.Email, &u.HashedPassword, &u.FirstName, &u.LastName,
		&u.IsActive, &u.IsSuperuser, &u.IsVerified, &u.CreatedAt)
	return u, err
}

type UpdateUserPasswordParams struct {
	ID             uuid.UUID
	HashedPassword *string
}

const updateUserPassword = `UPDATE users SET hashed_password = $2 WHERE id = $1`

func (q *Queries) UpdateUserPassword(ctx context.Context, arg UpdateUserPasswordParams) error {
	_, err := q.db.Exec(ctx, updateUserPassword, arg.ID, arg.HashedPassword)
	return err
}

const deleteUser = `DELETE FROM users WHERE id = $1`

func (q *Queries) DeleteUser(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteUser, id)
	return err
}

type GetOAuthAccountParams struct {
	OauthName string
	AccountID string
}

const getOAuthAccount = `SELECT id, user_id, oauth_name, account_id, account_email FROM oauth_account WHERE oauth_name = $1 AND account_id = $2 LIMIT 1`

func (q *Queries) GetOAuthAccount(ctx context.Context, arg GetOAuthAccountParams) (OauthAccount, error) {
	row := q.db.QueryRow(ctx, getOAuthAccount, arg.OauthName, arg.AccountID)
	var o OauthAccount
	err := row.Scan(&o.ID, &o.UserID, &o.OauthName, &o.AccountID, &o.AccountEmail)
	return o, err
}

type CreateOAuthAccountParams struct {
	UserID       uuid.UUID
	OauthName    string
	AccountID    string
	AccountEmail string
}

const createOAuthAccount = `INSERT INTO oauth_account (user_id, oauth_name, account_id, account_email) VALUES ($1, $2, $3, $4) RETURNING id, user_id, oauth_name, account_id, account_email`

func (q *Queries) CreateOAuthAccount(ctx context.Context, arg CreateOAuthAccountParams) (OauthAccount, error) {
	row := q.db.QueryRow(ctx, createOAuthAccount, arg.UserID, arg.OauthName, arg.AccountID, arg.AccountEmail)
	var o OauthAccount
	err := row.Scan(&o.ID, &o.UserID, &o.OauthName, &o.AccountID, &o.AccountEmail)
	return o, err
}
